import { one, query } from "../shared/repository.js";
import { RequestError } from "../shared/http.js";
export async function assertCouponStore(storeId, userId) { const store = await one("SELECT id FROM ld_stores WHERE id = ? AND user_id = ?", [storeId, userId]); if (!store) throw new RequestError(404, "Loja não encontrada."); return store; }
export async function listCouponRows(storeId, filters, timestamp) { const where = ["store_id = ?"]; const params = [storeId]; if (filters.query) { where.push("code LIKE ?"); params.push(`%${filters.query}%`); } if (filters.status === "active") where.push("active = 1"); if (filters.status === "inactive") where.push("active = 0"); if (filters.status === "expired") { where.push("expires_at IS NOT NULL AND expires_at < ?"); params.push(timestamp); } const predicate = where.join(" AND "); const [total, summary, rows] = await Promise.all([one(`SELECT COUNT(*) AS total FROM ld_coupons WHERE ${predicate}`, params), one("SELECT COUNT(*) AS total, SUM(active = 1) AS active, SUM(discount_type = 'free_shipping') AS free_shipping, SUM(usage_count) AS uses FROM ld_coupons WHERE store_id = ?", [storeId]), query(`SELECT * FROM ld_coupons WHERE ${predicate} ORDER BY created_at DESC LIMIT ${filters.limit} OFFSET ${filters.offset}`, params)]); return { total: Number(total?.total || 0), summary, rows }; }
export async function findCoupon(storeId, couponId) { return one("SELECT * FROM ld_coupons WHERE id = ? AND store_id = ?", [couponId, storeId]); }
export async function customerHasPurchases(storeId, customerId) { return one("SELECT purchases.id FROM ld_customer_purchases AS purchases JOIN ld_customers AS customers ON customers.id = purchases.customer_id WHERE customers.store_id = ? AND customers.id = ? LIMIT 1", [storeId, customerId]); }
export async function insertCoupon(coupon) { await query("INSERT INTO ld_coupons (id, store_id, code, discount_type, percentage_off, amount_off_cents, minimum_order_cents, expires_at, usage_limit, usage_count, free_shipping_states, active, new_users_only, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 0, ?, ?, ?, ?, ?)", [coupon.id, coupon.storeId, coupon.code, coupon.discountType, coupon.percentageOff, coupon.amountOffCents, coupon.minimumOrderCents, coupon.expiresAt, coupon.usageLimit, JSON.stringify(coupon.freeShippingStates), coupon.active ? 1 : 0, coupon.newUsersOnly ? 1 : 0, coupon.createdAt, coupon.updatedAt]); }
export async function updateCoupon(storeId, couponId, input, timestamp) { await query("UPDATE ld_coupons SET code = ?, discount_type = ?, percentage_off = ?, amount_off_cents = ?, minimum_order_cents = ?, expires_at = ?, usage_limit = ?, free_shipping_states = ?, active = ?, new_users_only = ?, updated_at = ? WHERE id = ? AND store_id = ?", [input.code, input.discountType, input.percentageOff, input.amountOffCents, input.minimumOrderCents, input.expiresAt, input.usageLimit, JSON.stringify(input.freeShippingStates), input.active ? 1 : 0, input.newUsersOnly ? 1 : 0, timestamp, couponId, storeId]); }
export async function removeCoupon(storeId, couponId) { const result = await query("DELETE FROM ld_coupons WHERE id = ? AND store_id = ?", [couponId, storeId]); if (!result?.affectedRows) throw new RequestError(404, "Cupom não encontrado."); }
