import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({ navigate: vi.fn() }));
vi.mock("wouter", () => ({ Link: ({ children }) => <span>{children}</span>, useLocation: () => ["/dashboard", mocks.navigate] }));
vi.mock("@/contexts/ActiveStoreContext", () => ({ useActiveStore: () => ({ store: { id: "store-1", name: "Minha loja", catalog: { totalProducts: 8, activeProducts: 5, draftProducts: 2, archivedProducts: 1, categoriesWithProducts: 3, inventoryUnits: 21, outOfStockProducts: 1, lowStockProducts: 2, newProductsLast30Days: 4 } }, alerts: [{ storeId: "store-1", title: "Renovação próxima", description: "Renove seu plano", href: "/billing/orders" }] }) }));
vi.mock("@/i18n", () => ({ useI18n: () => ({ t: (key) => ({ "dashboard.myStore": "Minha loja", "dashboard.overview": "Visão geral", "dashboard.start": "Tudo certo", "dashboard.storeIntro": "A loja", "dashboard.storeReady": "está pronta", "dashboard.newStore": "Nova loja", "dashboard.operationStatus": "Status", "dashboard.storeLabel": "Loja", "dashboard.storeDetail": "Detalhe", "dashboard.trial": "Teste", "dashboard.plan": "Plano", "dashboard.trialDetail": "Detalhe", "dashboard.trialDays": "7 dias", "dashboard.addProducts": "Adicionar produtos", "dashboard.nextAction": "Próxima ação", "dashboard.catalogDetail": "Detalhe", "dashboard.startHere": "Comece", "dashboard.operationReady": "Operação pronta", "dashboard.operationDetail": "Detalhe", "dashboard.editStore": "Editar loja", "dashboard.catalogMetrics": "Métricas reais de catálogo", "dashboard.catalogForStore": "Catálogo de {name}", "dashboard.catalogOverview": "Visão operacional", "dashboard.catalogUpdated": "Atualizada conforme o catálogo salvo.", "dashboard.derivedIndicators": "Indicadores derivados:", "dashboard.derivedIndicatorsDetail": " Novo corresponde a produtos cadastrados nos últimos 30 dias. Mais vendido e destaque não são exibidos porque não existem pedidos de consumidor nesta aplicação para calculá-los com confiabilidade.", "dashboard.selectStoreForCatalogMetrics": "Selecione uma loja para consultar as métricas do catálogo." })[key] || key }) }));
import { DashboardContent } from "./DashboardPage.jsx";

describe("avisos e métricas do dashboard", () => { afterEach(() => cleanup()); it("mantém o aviso contextual de desktop, enquanto o ticker móvel é centralizado no shell", () => { render(<DashboardContent />); const alert = screen.getByRole("button", { name: /Renovação próxima/ }); expect(alert.className).toContain("relative"); fireEvent.click(alert); expect(mocks.navigate).toHaveBeenCalledWith("/billing/orders"); }); it("mostra métricas de catálogo persistidas e explica o limite de métricas de venda", () => { render(<DashboardContent />); expect(screen.getByText("Visão operacional")).toBeTruthy(); expect(screen.getByText("8")).toBeTruthy(); expect(screen.getByText("Unidades em estoque")).toBeTruthy(); expect(screen.getByText("21")).toBeTruthy(); expect(screen.getByText(/não existem pedidos de consumidor/i)).toBeTruthy(); }); });
