/** Loja Descomplicada: um início limpo e objetivo, orientado a atalhos comerciais sem inventar métricas. */
import { Link, useLocation } from "wouter";
import { AlertTriangle, ArrowRight, Boxes, CalendarDays, CircleCheck, Layers3, PackageX, Plus, Sparkles, Store, Warehouse } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "sonner";
import { useActiveStore } from "@/contexts/ActiveStoreContext";
import { useI18n } from "@/i18n";

export default function DashboardPage() {
  return <AppShell><DashboardContent /></AppShell>;
}

export function DashboardContent() {
  const [, navigate] = useLocation();
  const { t } = useI18n();
  const { store, alerts } = useActiveStore();
  const name = store?.name || t("dashboard.myStore");
  const alert = alerts?.find((item) => !store?.id || item.storeId === store.id) || alerts?.[0];
  const openProducts = () => navigate("/products");
  const catalog = store?.catalog;
  return <main className="px-5 py-8 pb-24 sm:px-8 sm:pb-8 lg:px-12">{alert && <button onClick={() => navigate(alert.href || "/billing/orders")} className="relative mb-5 hidden w-full items-start gap-3 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-left shadow-sm sm:flex"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-amber-700 dark:text-amber-300" /><span><strong className="block text-sm text-foreground">{alert.title}</strong><span className="mt-1 block text-sm text-muted-foreground">{alert.description}</span></span><ArrowRight className="ml-auto mt-1 size-4 shrink-0 text-muted-foreground" /></button>}<div className="flex flex-col justify-between gap-5 border-b pb-7 sm:flex-row sm:items-end"><div><p className="mb-3 text-[10px] font-bold uppercase tracking-[.18em] text-muted-foreground">{t("dashboard.overview")}</p><h1 className="font-display text-3xl font-bold tracking-[-.04em] text-foreground sm:text-4xl">{t("dashboard.start")}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">{t("dashboard.storeIntro")} <strong className="font-semibold text-foreground">{name}</strong> {t("dashboard.storeReady")}</p></div><Button variant="outline" className="shrink-0" onClick={() => navigate("/onboarding/store")}><Plus className="size-4" />{t("dashboard.newStore")}</Button></div>
    <section className="mx-auto mt-6 max-w-4xl" aria-label={t("dashboard.catalogMetrics")}>{store ? <><div className="mb-3 flex flex-wrap items-end justify-between gap-2"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-muted-foreground">{t("dashboard.catalogForStore").replace("{name}", store.name)}</p><h2 className="mt-1 text-lg font-bold tracking-tight">{t("dashboard.catalogOverview")}</h2></div><p className="text-xs text-muted-foreground">{t("dashboard.catalogUpdated")}</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><CatalogMetric icon={Boxes} label="Produtos" value={catalog?.totalProducts ?? 0} detail={`${catalog?.activeProducts ?? 0} ativos · ${catalog?.draftProducts ?? 0} rascunhos`} /><CatalogMetric icon={Layers3} label="Categorias usadas" value={catalog?.categoriesWithProducts ?? 0} detail={`${catalog?.archivedProducts ?? 0} arquivado(s)`} /><CatalogMetric icon={Warehouse} label="Unidades em estoque" value={catalog?.inventoryUnits ?? 0} detail={`${catalog?.lowStockProducts ?? 0} produto(s) com estoque baixo`} tone={(catalog?.lowStockProducts ?? 0) > 0 ? "warning" : "default"} /><CatalogMetric icon={PackageX} label="Sem estoque" value={catalog?.outOfStockProducts ?? 0} detail={`${catalog?.newProductsLast30Days ?? 0} produto(s) criados nos últimos 30 dias`} tone={(catalog?.outOfStockProducts ?? 0) > 0 ? "danger" : "default"} /></div><div className="mt-3 rounded-xl border border-dashed bg-muted/20 p-3 text-xs leading-5 text-muted-foreground"><strong className="text-foreground">{t("dashboard.derivedIndicators")}</strong>{t("dashboard.derivedIndicatorsDetail")}</div></> : <div className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">{t("dashboard.selectStoreForCatalogMetrics")}</div>}</section>
    <section className="mx-auto mt-6 max-w-4xl space-y-3" aria-label={t("dashboard.operationStatus")}><StatusCard icon={Store} title={name} label={t("dashboard.storeLabel")} detail={t("dashboard.storeDetail")} action={<CircleCheck className="size-5 text-sage" />} /><StatusCard icon={CalendarDays} title={t("dashboard.trial")} label={t("dashboard.plan")} detail={t("dashboard.trialDetail")} action={<span className="rounded-lg bg-muted px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-foreground">{t("dashboard.trialDays")}</span>} /><StatusCard icon={Sparkles} title={t("dashboard.addProducts")} label={t("dashboard.nextAction")} detail={t("dashboard.catalogDetail")} action={<ArrowRight className="size-5 text-muted-foreground" />} /></section>
    <section className="mx-auto flex max-w-3xl flex-col items-center py-12 text-center sm:py-16"><div className="mb-5 flex size-16 items-center justify-center rounded-2xl bg-muted"><Boxes className="size-7 text-foreground" /></div><span className="mb-4 text-[10px] font-bold uppercase tracking-[.16em] text-muted-foreground">{t("dashboard.startHere")}</span><h2 className="max-w-xl font-display text-2xl font-bold leading-tight tracking-[-.04em] text-foreground">{t("dashboard.operationReady")}</h2><p className="mt-3 max-w-md text-sm leading-6 text-muted-foreground">{t("dashboard.operationDetail")}</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Button onClick={openProducts}><Boxes className="size-4" />{t("dashboard.addProducts")}</Button>{store?.id && <Link href={`/stores/${store.id}/edit`} className="inline-flex h-11 items-center justify-center gap-2 rounded-[10px] border border-input bg-background px-5 text-sm font-bold text-foreground transition-colors hover:bg-secondary">{t("dashboard.editStore")} <ArrowRight className="size-4" /></Link>}</div></section>
  </main>;
}

function StatusCard({ icon: Icon, label, title, detail, action }) { return <Card className="border shadow-none"><CardContent className="flex items-center gap-4 p-4"><span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-muted text-foreground"><Icon className="size-4" /></span><span className="min-w-0 flex-1"><small className="block text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">{label}</small><strong className="mt-0.5 block truncate text-sm font-semibold text-foreground">{title}</strong><span className="mt-1 block text-xs leading-5 text-muted-foreground">{detail}</span></span><span className="shrink-0">{action}</span></CardContent></Card>; }
function CatalogMetric({ icon: Icon, label, value, detail, tone = "default" }) { return <Card className={tone === "danger" ? "border-destructive/30 bg-destructive/[.03] shadow-none" : tone === "warning" ? "border-amber-500/30 bg-amber-500/[.03] shadow-none" : "shadow-none"}><CardContent className="p-4"><span className="flex size-9 items-center justify-center rounded-lg bg-muted text-foreground"><Icon className="size-4" /></span><p className="mt-4 text-[10px] font-bold uppercase tracking-[.12em] text-muted-foreground">{label}</p><strong className="mt-1 block text-2xl font-bold tracking-tight">{value}</strong><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></CardContent></Card>; }
