import { AlertTriangle, LoaderCircle, Store } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useParams, useSearch } from "wouter";
import { PublicStoreShell, useStoreMetadata } from "@/components/storefront/PublicStoreShell";
import { PublicStoreProvider, usePublicStore } from "@/contexts/PublicStoreContext";
import { StorefrontBanners, StorefrontCategories, StorefrontMiniBanners, StorefrontProductDetail, StorefrontProductGrid, StorefrontSubcategoryNav } from "@/components/storefront/StorefrontSections";
import { selectActiveBanners, selectCatalogProductViewModels, selectCategoryViewModel, selectProductDetailViewModel, selectPublicPageViewModel, selectStorefrontProductBySlug, selectStorefrontShellViewModel, selectTopLevelCategories } from "@/domain/store-contract";
import { usePublicStoreDomain } from "@/hooks/usePublicStoreDomain";
import { publicStorePath } from "@/lib/public-store-url";
import { publicSlug, routeQueryValue } from "@/lib/route-params";

export default function PublicStorefrontPage({ screen = "home" }) {
  const params = useParams();
  const search = useSearch();
  const slug = publicSlug(params.slug);
  const state = usePublicStoreDomain(slug);
  if (state.status === "loading") return <PublicStoreLoading />;
  if (state.status === "invalid" || state.status === "not_found") return <PublicStoreNotFound error={state.error} />;
  if (state.status === "error" || !state.domain) return <PublicStoreUnavailable error={state.error} onRetry={state.reload} />;
  return <PublicStoreProvider domain={state.domain}><PublicStoreView screen={screen} params={params} search={search} /></PublicStoreProvider>;
}

function PublicStoreView({ screen, params, search }) {
  const { domain } = usePublicStore();
  const shell = selectStorefrontShellViewModel(domain);
  if (domain.store.identity.maintenance === true) return <PublicStoreMaintenance shell={shell} />;
  const base = publicStorePath(shell.store.slug);
  if (screen === "home") return <PublicHome domain={domain} shell={shell} base={base} />;
  if (screen === "category") return <PublicCategory domain={domain} shell={shell} base={base} categorySlug={publicSlug(params.categorySlug)} search={search} />;
  if (screen === "product") return <PublicProduct domain={domain} shell={shell} base={base} productSlug={publicSlug(params.productSlug)} />;
  if (screen === "search") return <PublicSearch domain={domain} shell={shell} base={base} search={search} />;
  if (screen === "page") return <PublicPage domain={domain} shell={shell} pageSlug={publicSlug(params.pageSlug)} />;
  return <PublicNotFound shell={shell} />;
}

function PublicHome({ domain, shell, base }) { useStoreMetadata(shell); const products = selectCatalogProductViewModels(domain); return <PublicStoreShell shell={shell}><StorefrontBanners banners={selectActiveBanners(domain)} base={base} /><StorefrontMiniBanners banners={domain.miniBanners} /><StorefrontCategories categories={selectTopLevelCategories(domain)} base={base} /><StorefrontProductGrid products={products.filter((product) => product.badges.featured).length ? products.filter((product) => product.badges.featured) : products} base={base} title={products.some((product) => product.badges.featured) ? "Destaques" : "Produtos"} emptyMessage="Esta loja ainda não possui produtos disponíveis." /></PublicStoreShell>; }
function PublicCategory({ domain, shell, base, categorySlug, search }) { const category = selectCategoryViewModel(domain, categorySlug); const selectedSubcategorySlug = new URLSearchParams(search).get("subcategoria"); const selectedSubcategory = category?.subcategories.find((item) => item.slug === selectedSubcategorySlug) || null; useStoreMetadata(shell, category ? { title: selectedSubcategory ? `${category.name} · ${selectedSubcategory.name}` : category.name, seo: {} } : {}); if (!category) return <PublicStoreShell shell={shell}><PublicNotFound shell={shell} compact /></PublicStoreShell>; const title = selectedSubcategory ? `${category.name} · ${selectedSubcategory.name}` : category.name; return <PublicStoreShell shell={shell}><StorefrontSubcategoryNav category={category} base={base} selectedSlug={selectedSubcategory?.slug || null} /><StorefrontProductGrid products={selectCatalogProductViewModels(domain, { categorySlug, subcategoryId: selectedSubcategory?.id || null })} base={base} title={title} description={category.description || "Categoria"} emptyMessage="Nenhum produto disponível nesta categoria." /></PublicStoreShell>; }
function PublicProduct({ domain, shell, base, productSlug }) { const { locale, currency } = usePublicStore(); const product = selectStorefrontProductBySlug(domain, productSlug); const [variantId, setVariantId] = useState(null); useEffect(() => setVariantId(product?.variants[0]?.id || null), [product?.id]); const detail = product ? selectProductDetailViewModel(product, variantId, locale, currency) : null; useStoreMetadata(shell, detail ? { title: detail.name, seo: {} } : {}); if (!detail) return <PublicStoreShell shell={shell}><PublicNotFound shell={shell} compact /></PublicStoreShell>; return <PublicStoreShell shell={shell}><StorefrontProductDetail product={detail} base={base} onVariantChange={setVariantId} /></PublicStoreShell>; }
function PublicSearch({ domain, shell, base, search }) { const initialQuery = routeQueryValue(search, "q"); const [query, setQuery] = useState(initialQuery); useEffect(() => setQuery(initialQuery), [initialQuery]); useStoreMetadata(shell, { title: `Buscar | ${shell.store.name}`, seo: {} }); return <PublicStoreShell shell={shell}><div className="mx-auto max-w-7xl px-4 pt-10 sm:px-6"><form onSubmit={(event) => event.preventDefault()}><label className="text-sm font-medium" htmlFor="public-search">Buscar na loja</label><input id="public-search" value={query} onChange={(event) => setQuery(event.target.value)} autoFocus className="mt-2 h-12 w-full max-w-xl rounded-xl border border-black/12 bg-white px-4 outline-none focus:border-[var(--store-primary)]" placeholder="Digite produto, categoria ou marca" /></form></div><StorefrontProductGrid products={selectCatalogProductViewModels(domain, { search: query })} base={base} title={query ? `Resultados para “${query}”` : "Todos os produtos"} emptyMessage="Nenhum produto corresponde à sua busca." /></PublicStoreShell>; }
function PublicPage({ domain, shell, pageSlug }) { const page = selectPublicPageViewModel(domain, pageSlug); useStoreMetadata(shell, page || {}); if (!page) return <PublicStoreShell shell={shell}><PublicNotFound shell={shell} compact /></PublicStoreShell>; return <PublicStoreShell shell={shell}><article className="mx-auto max-w-3xl px-4 py-12 sm:px-6"><h1 className="text-3xl font-semibold tracking-tight">{page.title}</h1>{page.content ? <div className="mt-6 whitespace-pre-line text-sm leading-7 text-black/70">{page.content}</div> : <p className="mt-6 text-sm text-black/60">Este conteúdo ainda não está disponível.</p>}</article></PublicStoreShell>; }
function PublicStoreLoading() { return <main className="min-h-screen bg-[var(--store-background,#fff)]" aria-label="Carregando loja"><header className="border-b border-black/10 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-5 sm:px-6"><span className="h-7 w-44 animate-pulse rounded bg-black/8" /><span className="h-10 w-24 animate-pulse rounded-xl bg-black/8" /></div></header><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="h-56 animate-pulse rounded-3xl bg-black/6 sm:h-72" /><div className="mt-10 grid grid-cols-2 gap-4 sm:grid-cols-4">{[0, 1, 2, 3].map((item) => <div key={item} className="h-24 animate-pulse rounded-2xl bg-black/6" />)}</div><div className="mt-10 grid gap-4 sm:grid-cols-3">{[0, 1, 2].map((item) => <div key={item} className="h-72 animate-pulse rounded-2xl bg-black/6" />)}</div></div></main>; }
function PublicStoreUnavailable({ error, onRetry }) { return <main className="grid min-h-screen place-items-center bg-black/[0.02] p-6"><div className="max-w-md rounded-2xl border border-black/10 bg-white p-8 text-center"><Store className="mx-auto size-8 text-black/40" /><h1 className="mt-4 text-xl font-semibold">Loja indisponível</h1><p className="mt-2 text-sm leading-6 text-black/60">{error || "Não foi possível carregar esta loja agora."}</p>{onRetry && <button type="button" onClick={onRetry} className="mt-5 rounded-xl bg-black px-4 py-2 text-sm font-semibold text-white transition active:scale-[.98]">Tentar novamente</button>}</div></main>; }
function PublicStoreNotFound({ error }) { return <main className="grid min-h-screen place-items-center bg-black/[0.02] p-6"><div className="max-w-md rounded-2xl border border-black/10 bg-white p-8 text-center"><Store className="mx-auto size-8 text-black/40" /><h1 className="mt-4 text-xl font-semibold">Loja não encontrada</h1><p className="mt-2 text-sm leading-6 text-black/60">{error || "O endereço informado não corresponde a uma loja pública disponível."}</p></div></main>; }
function PublicStoreMaintenance({ shell }) { useStoreMetadata(shell, { title: shell.store.name, seo: {} }); return <main className="grid min-h-screen place-items-center bg-black/[0.02] p-6"><div className="max-w-md rounded-2xl border border-black/10 bg-white p-8 text-center"><AlertTriangle className="mx-auto size-8 text-[var(--store-primary)]" /><h1 className="mt-4 text-xl font-semibold">Voltamos em breve</h1><p className="mt-2 text-sm leading-6 text-black/60">{shell.store.maintenanceMessage || "Esta loja está em manutenção."}</p></div></main>; }
function PublicNotFound({ shell, compact = false }) { const content = <div className="text-center"><AlertTriangle className="mx-auto size-7 text-black/35" /><h1 className="mt-3 text-xl font-semibold">Conteúdo não encontrado</h1><p className="mt-2 text-sm text-black/60">O conteúdo solicitado não está disponível nesta loja.</p></div>; return compact ? <section className="grid min-h-80 place-items-center px-4">{content}</section> : <main className="grid min-h-screen place-items-center bg-black/[0.02] p-6">{content}</main>; }
