import { one, query, transaction } from "../shared/repository.js";
export const withinTransaction = transaction;
export async function findStoreOwnedByUser(storeId, userId) { return one("SELECT id, name FROM ld_stores WHERE id = ? AND user_id = ?", [storeId, userId]); }
export async function findCategoryOwnedByUser(storeId, categoryId, userId) { return one("SELECT categories.* FROM ld_product_categories AS categories JOIN ld_stores AS stores ON stores.id = categories.store_id WHERE categories.id = ? AND categories.store_id = ? AND stores.user_id = ?", [categoryId, storeId, userId]); }
export async function findProductOwnedByUser(storeId, productId, userId) { return one("SELECT products.*, categories.name AS category_name FROM ld_products AS products JOIN ld_stores AS stores ON stores.id = products.store_id JOIN ld_product_categories AS categories ON categories.id = products.category_id WHERE products.id = ? AND products.store_id = ? AND stores.user_id = ?", [productId, storeId, userId]); }
export async function listCategories(storeId, search) { const params = [storeId]; let where = "categories.store_id = ?"; if (search) { where += " AND categories.name LIKE ?"; params.push(`%${search}%`); } return query(`SELECT categories.id, categories.store_id, categories.parent_category_id, categories.name, categories.description, categories.crop_aspect, categories.card_image_url, categories.hero_image_url, categories.active, categories.created_at, categories.updated_at, COUNT(products.id) AS product_count FROM ld_product_categories AS categories LEFT JOIN ld_products AS products ON products.category_id = categories.id WHERE ${where} GROUP BY categories.id ORDER BY categories.parent_category_id IS NOT NULL, categories.active DESC, categories.name ASC LIMIT 500`, params); }
export async function findCategoryByName(storeId, name, excludeId = null) { return excludeId ? one("SELECT id FROM ld_product_categories WHERE store_id = ? AND name = ? AND id <> ?", [storeId, name, excludeId]) : one("SELECT id FROM ld_product_categories WHERE store_id = ? AND name = ?", [storeId, name]); }
export async function insertCategory(category) { await query("INSERT INTO ld_product_categories (id, store_id, parent_category_id, name, description, crop_aspect, card_image_url, hero_image_url, active, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [category.id, category.storeId, category.parentCategoryId, category.name, category.description, category.cropAspect, category.cardImageUrl, category.heroImageUrl, category.active ? 1 : 0, category.createdAt, category.updatedAt]); }
export async function updateCategory(category, input, timestamp) { await query("UPDATE ld_product_categories SET parent_category_id = ?, name = ?, description = ?, crop_aspect = ?, card_image_url = ?, hero_image_url = ?, active = ?, updated_at = ? WHERE id = ?", [input.parentCategoryId, input.name, input.description, input.cropAspect, input.cardImageUrl, input.heroImageUrl, input.active ? 1 : 0, timestamp, category.id]); }
export async function findCategoryInStore(storeId, categoryId) { return one("SELECT * FROM ld_product_categories WHERE id = ? AND store_id = ?", [categoryId, storeId]); }
export async function listCategoryTree(storeId, categoryId) { return query("SELECT id, parent_category_id FROM ld_product_categories WHERE store_id = ? AND (id = ? OR parent_category_id = ?)", [storeId, categoryId, categoryId]); }
export async function hasProductsInCategories(categoryIds) { if (!categoryIds.length) return null; return one(`SELECT id FROM ld_products WHERE category_id IN (${categoryIds.map(() => "?").join(", ")}) LIMIT 1`, categoryIds); }
export async function deleteCategory(categoryId) { await query("DELETE FROM ld_product_categories WHERE id = ?", [categoryId]); }
export async function listCategoryProductStorageKeys(categoryIds) { if (!categoryIds.length) return []; return query(`SELECT media.storage_key FROM ld_product_media AS media JOIN ld_products AS products ON products.id = media.product_id WHERE products.category_id IN (${categoryIds.map(() => "?").join(", ")})`, categoryIds); }
export async function deleteProductsInCategories(tx, categoryIds) { if (categoryIds.length) await tx.query(`DELETE FROM ld_products WHERE category_id IN (${categoryIds.map(() => "?").join(", ")})`, categoryIds); }
export async function deleteCategoryTreeInTransaction(tx, rootCategoryId) { await tx.query("DELETE FROM ld_product_categories WHERE parent_category_id = ?", [rootCategoryId]); await tx.query("DELETE FROM ld_product_categories WHERE id = ?", [rootCategoryId]); }
export async function listProductPage({ filters, pagination, sort }) { const [count, rows] = await Promise.all([one(`SELECT COUNT(*) AS total FROM ld_products AS products WHERE ${filters.where}`, filters.params), query(`SELECT products.*, categories.name AS category_name, (SELECT media.url FROM ld_product_media AS media WHERE media.product_id = products.id AND media.kind = 'image' ORDER BY media.is_primary DESC, media.sort_order ASC LIMIT 1) AS main_image_url, (SELECT COUNT(*) FROM ld_product_variants AS variants WHERE variants.product_id = products.id) AS variant_count FROM ld_products AS products JOIN ld_product_categories AS categories ON categories.id = products.category_id WHERE ${filters.where} ORDER BY ${sort} LIMIT ${pagination.limit} OFFSET ${pagination.offset}`, filters.params)]); return { count, rows }; }
export async function listProductMedia(productId) { return query("SELECT * FROM ld_product_media WHERE product_id = ? ORDER BY kind ASC, sort_order ASC", [productId]); }
export async function listProductVariants(productId) { return query("SELECT * FROM ld_product_variants WHERE product_id = ? ORDER BY sort_order ASC, created_at ASC", [productId]); }
export async function listProductMediaInTransaction(tx, productId) { return tx.query("SELECT * FROM ld_product_media WHERE product_id = ? ORDER BY kind ASC, sort_order ASC", [productId]); }
export async function listProductStorageKeys(productId) { return query("SELECT storage_key FROM ld_product_media WHERE product_id = ?", [productId]); }
export async function findProductMedia(productId, mediaId) { return one("SELECT * FROM ld_product_media WHERE id = ? AND product_id = ?", [mediaId, productId]); }
export async function findProductBySku(storeId, sku, excludeId = null) { return excludeId ? one("SELECT id FROM ld_products WHERE store_id = ? AND sku = ? AND id <> ?", [storeId, sku, excludeId]) : one("SELECT id FROM ld_products WHERE store_id = ? AND sku = ?", [storeId, sku]); }
export async function deleteProduct(productId) { await query("DELETE FROM ld_products WHERE id = ?", [productId]); }
export async function deleteProductMedia(mediaId) { await query("DELETE FROM ld_product_media WHERE id = ?", [mediaId]); }
export async function normalizeImageOrder(productId) { const images = await query("SELECT id FROM ld_product_media WHERE product_id = ? AND kind = 'image' ORDER BY sort_order ASC, created_at ASC", [productId]); await Promise.all(images.map((item, index) => query("UPDATE ld_product_media SET sort_order = ?, is_primary = ? WHERE id = ?", [index, index === 0 ? 1 : 0, item.id]))); }
export async function listStagedUploadKinds(storeId, userId, draftId) { return query("SELECT kind FROM ld_product_uploads WHERE store_id = ? AND user_id = ? AND draft_id = ? AND status = 'staged'", [storeId, userId, draftId]); }
export async function insertStagedUpload(media) { await query("INSERT INTO ld_product_uploads (id, store_id, user_id, draft_id, kind, storage_key, url, content_type, file_size, status, created_at, expires_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'staged', ?, ?)", [media.id, media.storeId, media.userId, media.draftId, media.kind, media.storageKey, media.url, media.contentType, media.fileSize, media.createdAt, media.expiresAt]); }
export async function findStagedUpload(storeId, userId, uploadId) { return one("SELECT * FROM ld_product_uploads WHERE id = ? AND store_id = ? AND user_id = ? AND status = 'staged'", [uploadId, storeId, userId]); }
export async function deleteStagedUpload(uploadId) { await query("DELETE FROM ld_product_uploads WHERE id = ? AND status = 'staged'", [uploadId]); }
export async function findCategoryInStoreTx(tx, categoryId, storeId) { return tx.one("SELECT id, name, active FROM ld_product_categories WHERE id = ? AND store_id = ?", [categoryId, storeId]); }
export async function lockStagedUploads(tx, { storeId, userId, draftId, uploadIds }) { const placeholders = uploadIds.map(() => "?").join(", "); return tx.query(`SELECT * FROM ld_product_uploads WHERE id IN (${placeholders}) AND store_id = ? AND user_id = ? AND draft_id = ? AND status = 'staged' AND expires_at > ? FOR UPDATE`, [...uploadIds, storeId, userId, draftId, Date.now()]); }
export async function insertProduct(tx, product) { await tx.query("INSERT INTO ld_products (id, store_id, category_id, name, sku, description, short_description, price_cents, compare_at_price_cents, cost_price_cents, brand, tags_json, stock_quantity, weight_grams, width_mm, height_mm, depth_mm, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [product.id, product.storeId, product.categoryId, product.name, product.sku || null, product.description, product.shortDescription, product.priceCents, product.compareAtPriceCents, product.costPriceCents, product.brand, JSON.stringify(product.tags), product.stockQuantity, product.weightGrams, product.widthMm, product.heightMm, product.depthMm, product.status, product.createdAt, product.updatedAt]); }
export async function updateProduct(tx, product) { await tx.query("UPDATE ld_products SET category_id = ?, name = ?, sku = ?, description = ?, short_description = ?, price_cents = ?, compare_at_price_cents = ?, cost_price_cents = ?, brand = ?, tags_json = ?, stock_quantity = ?, weight_grams = ?, width_mm = ?, height_mm = ?, depth_mm = ?, status = ?, updated_at = ? WHERE id = ?", [product.categoryId, product.name, product.sku || null, product.description, product.shortDescription, product.priceCents, product.compareAtPriceCents, product.costPriceCents, product.brand, JSON.stringify(product.tags), product.stockQuantity, product.weightGrams, product.widthMm, product.heightMm, product.depthMm, product.status, product.updatedAt, product.id]); }
export async function replaceProductVariants(tx, productId, variants, timestamp) { await tx.query("DELETE FROM ld_product_variants WHERE product_id = ?", [productId]); for (const [index, variant] of variants.entries()) await tx.query("INSERT INTO ld_product_variants (id, product_id, name, sku, price_cents, stock_quantity, sort_order, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", [crypto.randomUUID(), productId, variant.name, variant.sku || null, variant.priceCents, variant.stockQuantity, index, timestamp, timestamp]); }
export async function attachUploads(tx, { productId, uploads, timestamp, startOrder }) { const images = uploads.filter((item) => item.kind === "image"); const video = uploads.find((item) => item.kind === "video"); for (const [index, item] of images.entries()) await tx.query("INSERT INTO ld_product_media (id, product_id, kind, storage_key, url, content_type, file_size, sort_order, is_primary, created_at, updated_at) VALUES (?, ?, 'image', ?, ?, ?, ?, ?, ?, ?, ?)", [crypto.randomUUID(), productId, item.storage_key, item.url, item.content_type, item.file_size, startOrder + index, startOrder + index === 0 ? 1 : 0, timestamp, timestamp]); if (video) await tx.query("INSERT INTO ld_product_media (id, product_id, kind, storage_key, url, content_type, file_size, sort_order, is_primary, created_at, updated_at) VALUES (?, ?, 'video', ?, ?, ?, ?, 0, 0, ?, ?)", [crypto.randomUUID(), productId, video.storage_key, video.url, video.content_type, video.file_size, timestamp, timestamp]); await tx.query(`UPDATE ld_product_uploads SET status = 'attached', attached_at = ? WHERE id IN (${uploads.map(() => "?").join(", ")})`, [timestamp, ...uploads.map((item) => item.id)]); }
