import { Router } from "express";
import authRouter from "./modules/auth/routes.js";
import accountRouter from "./modules/account/routes.js";
import storeRouter, { publicStoreDeletionRouter } from "./modules/stores/routes.js";
import billingRouter from "./modules/billing/routes.js";
import webhookRouter from "./modules/webhooks/mercado-pago.js";
import dashboardRouter from "./modules/dashboard/routes.js";
import productRouter from "./modules/products/routes.js";
import customerRouter from "./modules/customers/routes.js";
import couponRouter from "./modules/coupons/routes.js";
import bannerRouter from "./modules/banners/routes.js";
import integrationRouter, { publicIntegrationRouter } from "./modules/integrations/routes.js";
import storeContractRouter, { publicStoreContractRouter } from "./modules/store-contract/routes.js";
import addressRouter from "./modules/address/routes.js";
import storefrontRouter from "./modules/storefront/routes.js";
import orderRouter from "./modules/orders/routes.js";
import { requireUser } from "./modules/auth/middleware.js";
import { enforceRateLimit, enforceRequestLimits } from "./modules/shared/http.js";
import { apiErrorHandler } from "./modules/shared/response.js";
import { reconcileAllStores, reconcileStoresForUser, billingLifecycle, buildMercadoPagoOrderPayload, isCollectorPayer, mercadoPagoOrderFailure, originFor, preapprovalRejectionGuidance, providerIssueSummary, trialEndsAtFrom, verifyMercadoPagoSignature } from "./modules/billing/service.js";
import { normalizeStoreProfile } from "./modules/stores/service.js";
import { sendResetEmail } from "./modules/auth/email.js";

const router = Router();
router.use(enforceRateLimit);
router.use(enforceRequestLimits);
router.use(authRouter);
router.use(webhookRouter);
router.use(publicIntegrationRouter);
router.use(publicStoreDeletionRouter);
router.use(publicStoreContractRouter);
router.use(storefrontRouter);
router.use(addressRouter);
router.use(requireUser);
router.use(async (req, _res, next) => { try { await reconcileStoresForUser(req.user.id); next(); } catch (error) { next(error); } });
router.use(accountRouter);
router.use(storeRouter);
router.use(billingRouter);
router.use(dashboardRouter);
router.use(productRouter);
router.use(customerRouter);
router.use(orderRouter);
router.use(couponRouter);
router.use(bannerRouter);
router.use(integrationRouter);
router.use(storeContractRouter);
router.use(apiErrorHandler);

export { billingLifecycle, buildMercadoPagoOrderPayload, isCollectorPayer, mercadoPagoOrderFailure, normalizeStoreProfile, originFor, preapprovalRejectionGuidance, providerIssueSummary, reconcileAllStores, sendResetEmail, trialEndsAtFrom, verifyMercadoPagoSignature };
export default router;
