import express from "express";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({ one: vi.fn(), query: vi.fn(), transaction: vi.fn(), put: vi.fn(), remove: vi.fn() }));
vi.mock("./modules/storage/media-storage.js", () => ({ getProductStorage: () => ({ put: mocks.put, remove: mocks.remove }), bannerMediaKey: ({ accountId, storeId, bannerId, breakpoint, assetId, extension }) => `${accountId}/${storeId}/banners/${bannerId}/${breakpoint}/${assetId}.${extension}` }));
vi.mock("./modules/banners/../../db.js", () => ({ one: mocks.one, query: mocks.query, transaction: mocks.transaction }));
vi.mock("./modules/store-contract/r2-sync.js", () => ({ syncStoreContractToR2: vi.fn().mockResolvedValue({ key: "loja-teste.json" }) }));
import bannerRouter from "./modules/banners/routes.js";

const baseBanner = { id: "banner-1", store_id: "store-1", title: "Principal", pages: "[\"home\"]", category_ids: "[]", display_position: "top", active: 1, created_at: 1, updated_at: 1 };
function app() { const server = express(); server.use(express.json()); server.use((req, _res, next) => { req.user = { id: "user-1" }; next(); }); server.use(bannerRouter); server.use((error, _req, res, _next) => res.status(error.status || 500).json({ error: error.message })); return server; }
async function withServer(callback) { const server = app(); const listener = await new Promise((resolve) => { const result = server.listen(0, () => resolve(result)); }); try { return await callback(`http://127.0.0.1:${listener.address().port}`); } finally { await new Promise((resolve) => listener.close(resolve)); } }
async function request(base, path, options = {}) { const response = await fetch(`${base}${path}`, options); return { status: response.status, body: await response.json() }; }
function png(width, height) { const buffer = Buffer.alloc(33); Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]).copy(buffer, 0); buffer.writeUInt32BE(13, 8); buffer.write("IHDR", 12); buffer.writeUInt32BE(width, 16); buffer.writeUInt32BE(height, 20); buffer[24] = 8; buffer[25] = 2; return buffer; }

describe("rotas HTTP de banners por loja", () => {
  beforeEach(() => { mocks.one.mockReset(); mocks.query.mockReset(); mocks.transaction.mockReset(); mocks.put.mockReset(); mocks.remove.mockReset(); mocks.transaction.mockImplementation((callback) => callback({ one: mocks.one, query: mocks.query })); mocks.remove.mockResolvedValue(undefined); });
  afterEach(() => vi.restoreAllMocks());

  it("bloqueia a listagem em loja sem posse", async () => { mocks.one.mockResolvedValue(null); const result = await withServer((base) => request(base, "/stores/store-alheia/banners")); expect(result.status).toBe(404); expect(result.body.error).toBe("Loja não encontrada."); });
  it("lista e cria banners no escopo da loja", async () => { mocks.one.mockResolvedValue({ id: "store-1" }); mocks.query.mockResolvedValueOnce([baseBanner]).mockResolvedValueOnce([]).mockResolvedValueOnce({ affectedRows: 1 }); await withServer(async (base) => { const listed = await request(base, "/stores/store-1/banners"); expect(listed.status).toBe(200); expect(listed.body.banners[0]).toMatchObject({ id: "banner-1", position: "top" }); const created = await request(base, "/stores/store-1/banners", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: "Campanha", pages: ["home", "products"], categoryIds: [], position: "middle", active: true }) }); expect(created.status).toBe(201); expect(created.body.banner).toMatchObject({ title: "Campanha", pages: ["home", "products"], position: "middle" }); }); });
  it("edita e exclui banner da loja ativa", async () => { const categoryId = "11111111-1111-4111-8111-111111111111"; mocks.one.mockResolvedValueOnce({ id: "store-1" }).mockResolvedValueOnce(baseBanner); mocks.query.mockResolvedValueOnce([{ id: categoryId }]).mockResolvedValueOnce({ affectedRows: 1 }).mockResolvedValueOnce([]); await withServer(async (base) => { const updated = await request(base, "/stores/store-1/banners/banner-1", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: "Atualizado", pages: ["categories"], categoryIds: [categoryId], position: "after_row_3", active: false }) }); expect(updated.status).toBe(200); expect(updated.body.banner).toMatchObject({ title: "Atualizado", position: "after_row_3", active: false }); }); mocks.one.mockResolvedValueOnce({ id: "store-1" }).mockResolvedValueOnce(baseBanner); mocks.query.mockResolvedValueOnce([]).mockResolvedValueOnce({ affectedRows: 1 }); const deleted = await withServer((base) => request(base, "/stores/store-1/banners/banner-1", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: "{}" })); expect(deleted.status).toBe(200); expect(deleted.body).toEqual({ ok: true }); });
  it("valida dimensões mínimas, upload e remoção de imagem", async () => { mocks.one.mockResolvedValue({ id: "store-1" }); await withServer(async (base) => { const tooSmall = new FormData(); tooSmall.append("breakpoint", "desktop"); tooSmall.append("file", new Blob([png(100, 100)], { type: "image/png" }), "small.png"); const invalid = await request(base, "/stores/store-1/banners/banner-1/media", { method: "POST", body: tooSmall }); expect(invalid.status).toBe(422); expect(invalid.body.error).toContain("1280×360"); }); mocks.one.mockResolvedValue({ id: "store-1" }); mocks.query.mockResolvedValueOnce([]).mockResolvedValueOnce({ affectedRows: 1 }); mocks.put.mockResolvedValue({ key: "user-1/store-1/banners/banner-1/desktop/media-1.png", url: "https://cdn.example/user-1/store-1/banners/banner-1/desktop/media-1.png" }); await withServer(async (base) => { const form = new FormData(); form.append("breakpoint", "desktop"); form.append("file", new Blob([png(1280, 360)], { type: "image/png" }), "desktop.png"); const uploaded = await request(base, "/stores/store-1/banners/banner-1/media", { method: "POST", body: form }); expect(uploaded.status).toBe(201); expect(uploaded.body.image).toMatchObject({ breakpoint: "desktop", width: 1280, height: 360 }); }); mocks.one.mockResolvedValueOnce({ id: "store-1" }).mockResolvedValueOnce(baseBanner).mockResolvedValueOnce({ id: "media-1", banner_id: "banner-1", storage_key: "user-1/store-1/banners/banner-1/desktop/media-1.png" }); mocks.query.mockResolvedValue({ affectedRows: 1 }); await withServer(async (base) => { const removed = await request(base, "/stores/store-1/banners/banner-1/media/media-1", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: "{}" }); expect(removed.status).toBe(200); }); expect(mocks.remove).toHaveBeenCalledWith("user-1/store-1/banners/banner-1/desktop/media-1.png"); });
  it("envia a imagem de rascunho ao storage antes de criar o banner", async () => { mocks.one.mockResolvedValue({ id: "store-1" }); mocks.query.mockResolvedValueOnce([]).mockResolvedValueOnce({ affectedRows: 1 }); mocks.put.mockResolvedValue({ key: "user-1/store-1/banners/draft-1/desktop/media-1.png", url: "https://cdn.example/user-1/store-1/banners/draft-1/desktop/media-1.png" }); await withServer(async (base) => { const form = new FormData(); form.append("draftId", "b1a7e30f-6055-4854-9e4b-4302444280cb"); form.append("breakpoint", "desktop"); form.append("file", new Blob([png(1280, 360)], { type: "image/png" }), "desktop.png"); const uploaded = await request(base, "/stores/store-1/banners/media", { method: "POST", body: form }); expect(uploaded.status).toBe(201); expect(uploaded.body.image).toMatchObject({ breakpoint: "desktop", url: "https://cdn.example/user-1/store-1/banners/draft-1/desktop/media-1.png" }); }); expect(mocks.put).toHaveBeenCalledTimes(1); });
  it("vincula um upload temporário ao criar o banner", async () => { const uploadId = "b1a7e30f-6055-4854-9e4b-4302444280cb"; const staged = { id: uploadId, breakpoint: "desktop", storage_key: "user-1/store-1/banners/draft/desktop/media.png", url: "https://cdn.example/user-1/store-1/banners/draft/desktop/media.png", content_type: "image/png", file_size: 1200, width: 1280, height: 360, crop_x: 50, crop_y: 50, crop_zoom: 1, created_at: 1 }; mocks.one.mockResolvedValue({ id: "store-1" }); mocks.query.mockResolvedValueOnce([staged]).mockResolvedValue({ affectedRows: 1 }); await withServer(async (base) => { const created = await request(base, "/stores/store-1/banners", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: "Com imagem", pages: ["home"], categoryIds: [], position: "top", active: true, draftId: uploadId, uploadIds: [uploadId] }) }); expect(created.status).toBe(201); expect(created.body.banner.images).toEqual([expect.objectContaining({ url: staged.url, stagedUploadId: uploadId })]); }); });
});
