CREATE TABLE IF NOT EXISTS ld_store_profiles (
  store_id CHAR(36) PRIMARY KEY,
  font_family VARCHAR(40) NOT NULL DEFAULT 'inter',
  contact_email VARCHAR(320) NOT NULL DEFAULT '',
  contact_phone VARCHAR(40) NOT NULL DEFAULT '',
  whatsapp_phone VARCHAR(40) NOT NULL DEFAULT '',
  support_hours VARCHAR(160) NOT NULL DEFAULT '',
  address_postal_code VARCHAR(20) NOT NULL DEFAULT '',
  address_street VARCHAR(180) NOT NULL DEFAULT '',
  address_number VARCHAR(30) NOT NULL DEFAULT '',
  address_complement VARCHAR(120) NOT NULL DEFAULT '',
  address_district VARCHAR(120) NOT NULL DEFAULT '',
  address_city VARCHAR(120) NOT NULL DEFAULT '',
  address_state VARCHAR(80) NOT NULL DEFAULT '',
  address_country CHAR(2) NOT NULL DEFAULT 'BR',
  instagram_url VARCHAR(320) NOT NULL DEFAULT '',
  facebook_url VARCHAR(320) NOT NULL DEFAULT '',
  tiktok_url VARCHAR(320) NOT NULL DEFAULT '',
  youtube_url VARCHAR(320) NOT NULL DEFAULT '',
  pinterest_url VARCHAR(320) NOT NULL DEFAULT '',
  twitter_url VARCHAR(320) NOT NULL DEFAULT '',
  favicon_url VARCHAR(800) NULL,
  settings_json JSON NULL,
  payment_methods_json JSON NULL,
  shipping_methods_json JSON NULL,
  about_title VARCHAR(160) NOT NULL DEFAULT '',
  about_body TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  CONSTRAINT ld_store_profiles_store_fk FOREIGN KEY (store_id) REFERENCES ld_stores(id) ON DELETE CASCADE
);
