import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { AlertTriangle, BarChart3, Boxes, ChevronDown, CircleHelp, Copy, Home, Images, LogOut, Moon, MoreHorizontal, Package, Pencil, Plus, Settings, ShoppingBag, Store, Sun, TicketPercent, UserCog, Users } from "lucide-react";
import { BrandMark } from "@/components/BrandMark";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerFooter, DrawerHeader, DrawerTitle, DrawerTrigger } from "@/components/ui/drawer";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { api } from "@/lib/api";
import { isApiError } from "@/lib/api-error";
import { clearActiveStoreCache, persistActiveStore, readActiveStoreCache } from "@/lib/active-store-cache";
import { toast } from "sonner";
import { ActiveStoreContext } from "@/contexts/ActiveStoreContext";
import { useI18n } from "@/i18n";

export function AppShell({ children, storeName }) {
  const [location, navigate] = useLocation();
  const { t } = useI18n();
  const navigation = [{ label: t("nav.home"), icon: Home, href: "/dashboard" }, { label: t("nav.orders"), icon: ShoppingBag, href: "/orders" }, { label: t("nav.customers"), icon: Users, href: "/customers" }, { label: t("nav.products"), icon: Package, href: "/products" }, { label: t("nav.coupons"), icon: TicketPercent, href: "/coupons" }, { label: t("nav.banners"), icon: Images, href: "/banners" }];
  const [store, setStore] = useState(() => readActiveStoreCache() || { id: "", name: storeName || t("nav.myStore") });
  const [stores, setStores] = useState([]);
  const [alerts, setAlerts] = useState([]);
  const [storesLoading, setStoresLoading] = useState(true);
  const [dark, setDark] = useState(() => document.documentElement.classList.contains("dark"));
  const toggleTheme = () => { document.documentElement.classList.toggle("dark"); setDark((value) => !value); };
  const logout = () => { localStorage.removeItem("ld_token"); clearActiveStoreCache(); navigate("/login"); };
  const refreshStores = () => {
    setStoresLoading(true);
    return api.getDashboard().then((result) => {
      const available = result.stores || [];
      setStores(available); setAlerts(result.alerts || []);
      const persisted = readActiveStoreCache();
      const active = resolveActiveStore(available, persisted);
      if (active) { setStore(active); persistActiveStore(active); }
      else { clearActiveStoreCache(); setStore({ id: "", name: storeName || t("nav.myStore") }); }
    }).catch((error) => {
      if (isApiError(error, 401)) { toast.error("Sua sessão expirou. Entre novamente para continuar."); logout(); return; }
      if (isApiError(error, 403)) toast.error("Você não tem permissão para acessar as lojas desta conta.");
    }).finally(() => setStoresLoading(false));
  };
  useEffect(() => { if (storeName) setStore((current) => ({ ...current, name: storeName })); }, [storeName]);
  useEffect(() => { refreshStores(); }, []);
  const chooseStore = (id) => { const selected = stores.find((item) => item.id === id); if (!selected) return; setStore(selected); persistActiveStore(selected); toast.success(t("nav.activeStore", { name: selected.name })); };
  const comingSoon = (label) => toast(t("nav.soon"), { description: t("nav.soonDescription", { label }) });
  const newStore = () => navigate("/onboarding/store");
  const editStore = () => store.id ? navigate(`/stores/${store.id}/edit`) : toast.error(t("nav.selectStoreToEdit"));
  const copyStoreLink = async () => { if (!store.id || !store.slug) return toast.error(t("nav.selectStoreToEdit")); const href = publicStoreLink(store, window.location.origin); try { await navigator.clipboard.writeText(href); toast.success(t("nav.copiedStoreLink")); } catch { toast.error(t("nav.copyStoreLinkError")); } };
  const alert = alerts?.find((item) => !store?.id || item.storeId === store.id) || alerts?.[0];

  return <ActiveStoreContext.Provider value={{ store, stores, alerts, storesLoading, chooseStore, refreshStores }}><div className="min-h-screen bg-background text-foreground lg:grid lg:grid-cols-[220px_minmax(0,1fr)]">
    <aside className="hidden self-start border-r bg-card p-4 lg:sticky lg:top-0 lg:flex lg:h-screen lg:flex-col"><BrandMark className="px-1" /><div className="my-6 h-px bg-border" /><nav className="space-y-1" aria-label={t("nav.mainNavigation")}>{navigation.map(({ label, icon: Icon, href }) => { const active = Boolean(href && (location === href || location.startsWith(`${href}/`))); return <button key={label} onClick={() => href ? navigate(href) : comingSoon(label)} className={cn("flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold transition-all", active ? "bg-muted text-foreground" : "nav-primary-hover text-muted-foreground")}><Icon className="size-4" />{label}</button>; })}</nav><div className="mt-auto space-y-1"><button onClick={() => navigate("/billing/orders")} className="nav-primary-hover flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-muted-foreground transition-all"><BarChart3 className="size-4" />{t("nav.subscriptions")}</button><button onClick={() => navigate("/settings")} className="nav-primary-hover flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-muted-foreground transition-all"><Settings className="size-4" />{t("nav.settings")}</button><button onClick={() => comingSoon(t("nav.help"))} className="nav-primary-hover flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-muted-foreground transition-all"><CircleHelp className="size-4" />{t("nav.help")}</button></div></aside>
    <div className="min-w-0 pb-20 lg:pb-0"><header className="sticky top-0 z-30 flex h-[60px] items-center justify-between border-b bg-background/95 px-4 backdrop-blur sm:px-6"><div className="lg:hidden"><BrandMark /></div><div className="hidden items-center gap-2 lg:flex"><Button variant="outline" size="icon" onClick={newStore} aria-label={t("nav.createStore")}><Plus className="size-4" /></Button><StoreSwitcher store={store} stores={stores} onChange={chooseStore} onCreate={newStore} t={t} /><Button variant="outline" size="icon" onClick={editStore} aria-label={t("nav.editStore")}><Pencil className="size-4" /></Button></div><div className="ml-auto flex items-center gap-2"><button onClick={toggleTheme} className="flex size-9 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-muted hover:text-foreground" aria-label={dark ? t("nav.lightTheme") : t("nav.darkTheme")}>{dark ? <Sun className="size-4" /> : <Moon className="size-4" />}</button><ProfileMenu onNavigate={navigate} onLogout={logout} t={t} /></div></header><GlobalMobileAlert alert={alert} onOpen={() => navigate(alert?.href || "/billing/orders")} />{children}</div>
    <nav className="fixed inset-x-0 bottom-0 z-40 flex h-[72px] items-center justify-around border-t bg-card px-2 pb-[max(env(safe-area-inset-bottom),8px)] pt-2 lg:hidden" aria-label={t("nav.mobileNavigation")}><MobileItem icon={ShoppingBag} label={t("nav.orders")} onClick={() => navigate("/orders")} /><MobileItem icon={Users} label={t("nav.customers")} onClick={() => navigate("/customers")} /><Drawer><DrawerTrigger asChild><button className="-mt-7 flex size-12 items-center justify-center text-foreground transition-transform hover:scale-110" aria-label={t("nav.openHomeStores")}><span className="primary-gradient flex size-9 items-center justify-center rounded-xl text-white"><ShoppingBag className="size-4" /></span></button></DrawerTrigger><HomeDrawer store={store} stores={stores} onStoreChange={chooseStore} onCreate={newStore} onEdit={editStore} onCopyLink={copyStoreLink} onHome={() => navigate("/dashboard")} t={t} /></Drawer><MobileItem icon={Package} label={t("nav.products")} onClick={() => navigate("/products")} /><Drawer><DrawerTrigger asChild><button className="flex w-14 flex-col items-center gap-1 text-muted-foreground"><MoreHorizontal className="size-5" /><span className="text-[10px] font-medium">{t("nav.more")}</span></button></DrawerTrigger><MoreDrawer onBilling={() => navigate("/billing/orders")} onCoupons={() => navigate("/coupons")} onBanners={() => navigate("/banners")} onSettings={() => navigate("/settings")} t={t} /></Drawer></nav>
  </div></ActiveStoreContext.Provider>;
}

function GlobalMobileAlert({ alert, onOpen }) { const [now, setNow] = useState(Date.now()); useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 60000); return () => window.clearInterval(timer); }, []); if (!alert) return null; const endsAt = Number(alert.trialEndsAt || alert.endsAt || 0); const inferredDays = Number(String(alert.description || alert.title || "").match(/\d+/)?.[0] || 0); const days = endsAt > now ? Math.max(1, Math.ceil((endsAt - now) / 86400000)) : inferredDays; const countdown = days ? `${days} ${days === 1 ? "dia" : "dias"}` : "Atenção necessária"; return <button type="button" onClick={onOpen} className="fixed inset-x-0 bottom-[4.4rem] z-40 flex h-8 items-center overflow-hidden border-y border-amber-500/30 bg-amber-500/10 text-left text-xs font-medium text-foreground lg:hidden" aria-label={`${alert.title}. ${countdown}`}><span className="dashboard-alert-ticker whitespace-nowrap"><AlertTriangle className="mr-2 inline size-3.5 text-amber-700" />{alert.title} · {countdown}     <AlertTriangle className="mr-2 inline size-3.5 text-amber-700" />{alert.title} · {countdown}     <AlertTriangle className="mr-2 inline size-3.5 text-amber-700" />{alert.title} · {countdown}</span></button>; }
function StoreSwitcher({ store, stores, onChange, onCreate, t, mobile = false }) { return <DropdownMenu><DropdownMenuTrigger asChild><button className={cn("flex h-9 items-center gap-2 rounded-lg border bg-background px-3 text-sm font-semibold transition-colors hover:bg-muted", mobile && "h-11 w-full justify-between")}><Store className="size-4 text-muted-foreground" /><span className="max-w-40 truncate">{store.name}</span><ChevronDown className="size-4 text-muted-foreground" /></button></DropdownMenuTrigger><DropdownMenuContent align="start" className="w-64"><DropdownMenuLabel>{t("nav.switchStore")}</DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuRadioGroup value={store.id} onValueChange={onChange}>{stores.map((item) => <DropdownMenuRadioItem key={item.id} value={item.id}><span className="truncate">{item.name}</span><span className="ml-auto text-xs text-muted-foreground">/@{item.slug}</span></DropdownMenuRadioItem>)}</DropdownMenuRadioGroup><DropdownMenuSeparator /><DropdownMenuItem onSelect={onCreate}><Plus className="size-4" />{t("nav.createStore")}</DropdownMenuItem></DropdownMenuContent></DropdownMenu>; }
function ProfileMenu({ onNavigate, onLogout, t }) { return <DropdownMenu><DropdownMenuTrigger asChild><button className="flex size-9 items-center justify-center rounded-full bg-muted text-muted-foreground transition-colors hover:text-foreground" aria-label={t("nav.openProfile")}><UserCog className="size-4" /></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>{t("nav.accountMenu")}</DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuItem onSelect={() => onNavigate("/account")}><UserCog className="size-4" />{t("nav.account")}</DropdownMenuItem><DropdownMenuItem onSelect={() => onNavigate("/account?tab=security")}><Pencil className="size-4" />{t("nav.changePassword")}</DropdownMenuItem><DropdownMenuSeparator /><DropdownMenuItem className="text-destructive focus:bg-destructive focus:text-destructive-foreground" onSelect={onLogout}><LogOut className="size-4" />{t("nav.signOut")}</DropdownMenuItem></DropdownMenuContent></DropdownMenu>; }
function MobileItem({ icon: Icon, label, onClick }) { return <button onClick={onClick} className="flex w-14 flex-col items-center gap-1 text-muted-foreground transition-colors hover:text-foreground"><Icon className="size-5" /><span className="text-[10px] font-medium">{label}</span></button>; }
export function HomeDrawer({ store, stores, onStoreChange, onCreate, onEdit, onCopyLink, onHome, t }) { return <DrawerContent className="flex max-h-[86vh] flex-col"><DrawerHeader><DrawerTitle>{t("nav.storesTitle")}</DrawerTitle><DrawerDescription>{t("nav.storesDescription")}</DrawerDescription></DrawerHeader><div className="min-h-0 flex-1 overflow-y-auto px-5 pb-3"><div className="space-y-2">{stores.map((item) => <button type="button" key={item.id} onClick={() => onStoreChange(item.id)} aria-pressed={store.id === item.id} className={cn("flex w-full items-center gap-3 rounded-xl border px-4 py-3 text-left text-sm font-semibold transition-colors", store.id === item.id ? "border-foreground bg-muted text-foreground" : "hover:bg-muted")}><Store className="size-4 shrink-0" /><span className="min-w-0 flex-1 truncate">{item.name}</span><small className="truncate text-xs font-normal text-muted-foreground">/@{item.slug}</small></button>)}</div><Button variant="outline" className="mt-3 w-full justify-start" onClick={onCreate}><Plus className="size-4" />{t("nav.createStore")}</Button></div><DrawerFooter className="border-t"><div className="flex gap-2"><DrawerClose asChild><Button className="min-w-0 flex-1 justify-start" onClick={onHome}><BarChart3 className="size-4" />{t("nav.homeStats")}</Button></DrawerClose><Button variant="outline" size="icon" onClick={onCopyLink} aria-label={t("nav.copyStoreLink")}><Copy className="size-4" /></Button><Button variant="outline" size="icon" onClick={onEdit} aria-label={t("nav.editStore")}><Pencil className="size-4" /></Button></div><p className="text-xs text-muted-foreground">{t("nav.newStorePlan")}</p></DrawerFooter></DrawerContent>; }
function MoreDrawer({ onBilling, onCoupons, onBanners, onSettings, t }) { return <DrawerContent><DrawerHeader><DrawerTitle>{t("nav.moreOptions")}</DrawerTitle><DrawerDescription>{t("nav.moreDescription")}</DrawerDescription></DrawerHeader><div className="divide-y border-y"><button onClick={onBilling} className="flex w-full items-center gap-3 px-5 py-4 text-left text-sm font-medium"><BarChart3 className="size-4" />{t("billing.title")}</button><button onClick={onCoupons} className="flex w-full items-center gap-3 px-5 py-4 text-left text-sm font-medium"><TicketPercent className="size-4" />{t("nav.coupons")}</button><button onClick={onBanners} className="flex w-full items-center gap-3 px-5 py-4 text-left text-sm font-medium"><Images className="size-4" />{t("nav.banners")}</button><button onClick={onSettings} className="flex w-full items-center gap-3 px-5 py-4 text-left text-sm font-medium"><Settings className="size-4" />{t("nav.settings")}</button>{[[Boxes, t("nav.reports")], [CircleHelp, t("nav.help")]].map(([Icon, label]) => <button key={label} className="flex w-full items-center gap-3 px-5 py-4 text-left text-sm font-medium text-muted-foreground"><Icon className="size-4" />{label}<span className="ml-auto text-[10px] font-semibold uppercase tracking-wide">{t("nav.comingSoon")}</span></button>)}</div></DrawerContent>; }
export function publicStoreLink(store, origin) { return store?.customDomain ? `https://${String(store.customDomain).replace(/^https?:\/\//, "")}` : `${String(origin || "").replace(/\/$/, "")}/@${store?.slug || ""}`; }
export function resolveActiveStore(stores, persisted) { const available = Array.isArray(stores) ? stores : []; return available.find((item) => item.id === persisted?.id) || available[0] || null; }
export { clearActiveStoreCache, persistActiveStore, readActiveStoreCache };
