import { useMemo, useState } from "react";
import { Check, ChevronDown, Search, X } from "lucide-react";
import { Input } from "@/components/ui/input";

const text = { search: "Buscar estado", placeholder: "Selecione os estados", remove: "Remover" };

export function ComboboxChips({ options, value = [], onChange, multiple = true, placeholder = text.placeholder }) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const selected = useMemo(() => new Set(value), [value]);
  const visible = options.filter((option) => `${option.label} ${option.value}`.toLowerCase().includes(query.toLowerCase()));
  const choose = (nextValue) => { if (!multiple) { onChange([nextValue]); setOpen(false); return; } onChange(selected.has(nextValue) ? value.filter((item) => item !== nextValue) : [...value, nextValue]); };
  return <div className="relative"><div className="flex min-h-11 flex-wrap items-center gap-1.5 rounded-lg border bg-background px-2 py-1.5 focus-within:ring-2 focus-within:ring-ring"><div className="flex min-w-0 flex-1 flex-wrap gap-1.5">{value.map((item) => { const option = options.find((entry) => entry.value === item); return <span key={item} className="inline-flex items-center gap-1 rounded-md bg-muted px-2 py-1 text-xs font-semibold">{option?.value || item}<button type="button" aria-label={`${text.remove} ${option?.label || item}`} onClick={() => onChange(value.filter((entry) => entry !== item))} className="rounded-sm text-muted-foreground hover:text-foreground"><X className="size-3" /></button></span>; })}</div><button type="button" aria-expanded={open} onClick={() => setOpen((current) => !current)} className="flex items-center gap-2 rounded-md px-2 py-1 text-sm text-muted-foreground hover:bg-muted hover:text-foreground">{value.length ? "" : placeholder}<ChevronDown className="size-4" /></button></div>{open && <div className="absolute z-40 mt-2 w-full rounded-xl border bg-popover p-2 text-popover-foreground shadow-xl"><div className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={text.search} className="pl-9" autoFocus /></div><div role="listbox" aria-multiselectable={multiple} className="mt-2 max-h-56 overflow-auto">{visible.map((option) => <button key={option.value} role="option" aria-selected={selected.has(option.value)} type="button" onClick={() => choose(option.value)} className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm hover:bg-muted"><span className={`flex size-4 items-center justify-center rounded border ${selected.has(option.value) ? "border-foreground bg-foreground text-background" : "border-input"}`}>{selected.has(option.value) && <Check className="size-3" />}</span><span className="font-semibold">{option.value}</span><span className="text-muted-foreground">{option.label}</span></button>)}</div></div>}</div>;
}
