import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { formatCurrencyInput } from "@/lib/input-formatters";

export function ProductCatalogFields({ form, setForm, section = "all" }) {
  const patch = (values) => setForm((current) => ({ ...current, ...values }));
  const updateVariant = (index, values) => patch({ variants: form.variants.map((variant, currentIndex) => currentIndex === index ? { ...variant, ...values } : variant) });
  const removeVariant = (index) => patch({ variants: form.variants.filter((_, currentIndex) => currentIndex !== index) });
  const addVariant = () => patch({ variants: [...form.variants, { localId: crypto.randomUUID(), name: "", sku: "", price: "", stockQuantity: "0" }] });

  const showIdentity = section === "all" || section === "identity";
  const showSales = section === "all" || section === "sales";
  const showLogistics = section === "all" || section === "logistics";
  return <section className={section === "all" ? "mt-8 space-y-6 border-t pt-7" : "space-y-6"} aria-label="Dados comerciais e estoque">
    {section === "all" && <div><h4 className="font-bold">Dados comerciais e estoque</h4><p className="mt-1 text-sm text-muted-foreground">Estes campos ficam no catálogo administrativo. Métricas de destaque, novidade e mais vendidos são calculadas pela plataforma.</p></div>}
    {showIdentity && <div className="grid gap-5 sm:grid-cols-2">
      <div className="space-y-2"><Label htmlFor="product-sku">SKU <span className="text-muted-foreground">(opcional)</span></Label><Input id="product-sku" value={form.sku} onChange={(event) => patch({ sku: event.target.value })} maxLength="120" placeholder="EX.: CAM-001" /></div>
      <div className="space-y-2"><Label htmlFor="product-brand">Marca <span className="text-muted-foreground">(opcional)</span></Label><Input id="product-brand" value={form.brand} onChange={(event) => patch({ brand: event.target.value })} maxLength="120" placeholder="Ex.: Linha própria" /></div>
      <div className="space-y-2 sm:col-span-2"><Label htmlFor="product-short-description">Descrição curta <span className="text-muted-foreground">(opcional)</span></Label><Input id="product-short-description" value={form.shortDescription} onChange={(event) => patch({ shortDescription: event.target.value })} maxLength="500" placeholder="Resumo exibido em listagens e vitrines." /></div>
      <div className="space-y-2 sm:col-span-2"><Label htmlFor="product-tags">Tags <span className="text-muted-foreground">(separadas por vírgula)</span></Label><Input id="product-tags" value={form.tags} onChange={(event) => patch({ tags: event.target.value })} maxLength="1200" placeholder="Ex.: algodão, básico, verão" /></div>
    </div>}
    {showSales && <><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
      <div className="space-y-2"><Label htmlFor="product-compare-price">Preço de origem</Label><Input id="product-compare-price" inputMode="numeric" placeholder="0,00" value={form.compareAtPrice} onChange={(event) => patch({ compareAtPrice: formatCurrencyInput(event.target.value) })} /></div>
      <div className="space-y-2"><Label htmlFor="product-cost-price">Preço de custo</Label><Input id="product-cost-price" inputMode="numeric" placeholder="0,00" value={form.costPrice} onChange={(event) => patch({ costPrice: formatCurrencyInput(event.target.value) })} /></div>
      <div className="space-y-2"><Label htmlFor="product-stock">Estoque</Label><Input id="product-stock" type="number" min="0" step="1" value={form.stockQuantity} onChange={(event) => patch({ stockQuantity: event.target.value })} /></div>
      <div className="space-y-2"><Label htmlFor="product-status">Status</Label><select id="product-status" className="h-10 w-full rounded-md border bg-background px-3 text-sm" value={form.status} onChange={(event) => patch({ status: event.target.value })}><option value="active">Ativo</option><option value="draft">Rascunho</option><option value="archived">Arquivado</option></select></div>
    </div>
    <div className="rounded-xl border bg-muted/20 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h5 className="text-sm font-bold">Variações</h5><p className="mt-1 text-xs text-muted-foreground">Cadastre tamanho, cor ou outra combinação pelo nome. O preço vazio usa o preço principal.</p></div><Button type="button" size="sm" variant="outline" onClick={addVariant}><Plus className="size-4" />Adicionar variação</Button></div>{form.variants.length ? <div className="mt-4 space-y-3">{form.variants.map((variant, index) => <div key={variant.localId} className="grid gap-3 rounded-lg border bg-background p-3 sm:grid-cols-[1.4fr_1.1fr_.8fr_.7fr_auto]"><Field id={`variant-name-${variant.localId}`} label="Nome" value={variant.name} onChange={(value) => updateVariant(index, { name: value })} required /><Field id={`variant-sku-${variant.localId}`} label="SKU" value={variant.sku} onChange={(value) => updateVariant(index, { sku: value })} /><div className="space-y-2"><Label htmlFor={`variant-price-${variant.localId}`}>Preço</Label><Input id={`variant-price-${variant.localId}`} inputMode="numeric" placeholder="Principal" value={variant.price} onChange={(event) => updateVariant(index, { price: formatCurrencyInput(event.target.value) })} /></div><Field id={`variant-stock-${variant.localId}`} label="Estoque" value={variant.stockQuantity} onChange={(value) => updateVariant(index, { stockQuantity: value })} /><Button type="button" variant="outline" size="icon" className="self-end text-destructive" aria-label={`Remover variação ${index + 1}`} onClick={() => removeVariant(index)}><Trash2 className="size-4" /></Button></div>)}</div> : <p className="mt-4 rounded-lg border border-dashed p-4 text-sm text-muted-foreground">Nenhuma variação cadastrada. O produto usará preço e estoque principais.</p>}</div>
    </>}
    {showLogistics && <div><h5 className="text-sm font-bold">Logística <span className="font-normal text-muted-foreground">(opcional)</span></h5><p className="mt-1 text-sm text-muted-foreground">Peso e dimensões ajudam a integração de frete a calcular serviços disponíveis.</p><div className="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field id="product-weight" label="Peso (g)" value={form.weightGrams} onChange={(value) => patch({ weightGrams: value })} /><Field id="product-width" label="Largura (mm)" value={form.widthMm} onChange={(value) => patch({ widthMm: value })} /><Field id="product-height" label="Altura (mm)" value={form.heightMm} onChange={(value) => patch({ heightMm: value })} /><Field id="product-depth" label="Profundidade (mm)" value={form.depthMm} onChange={(value) => patch({ depthMm: value })} /></div></div>}
  </section>;
}

function Field({ id, label, value, onChange, required = false }) { return <div className="space-y-2"><Label htmlFor={id}>{label}</Label><Input id={id} type={label.includes("Estoque") || label.includes("(g)") || label.includes("(mm)") ? "number" : "text"} min={label.includes("Estoque") || label.includes("(g)") || label.includes("(mm)") ? "0" : undefined} step={label.includes("Estoque") || label.includes("(g)") || label.includes("(mm)") ? "1" : undefined} value={value} onChange={(event) => onChange(event.target.value)} required={required} /></div>; }
