import { useEffect, useState } from "react";
import { AlertCircle, CheckCircle2, CircleDollarSign, CreditCard, ExternalLink, Globe2, LayoutTemplate, MapPinned, Palette, Store, Truck } from "lucide-react";
import { CollapsibleCard } from "@/components/CollapsibleCard";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { api } from "@/lib/api";
import { centsToCurrencyInput, currencyInputToCents } from "@/lib/input-formatters";

const DEFAULT_STOREFRONT = { maintenance: false, maintenanceMessage: "", currency: "BRL", locale: "pt-BR", timezone: "America/Sao_Paulo", template: "default", faviconUrl: "", theme: { secondaryColor: "", accentColor: "", backgroundColor: "", textColor: "" } };
const DEFAULT_SETTINGS = { freeShippingMinValue: null, maxInstallments: null, minInstallmentValue: null, showPriceFrom: true, showStock: true, showSoldCount: false, allowGuestCheckout: true, requireCpf: false, requirePhone: true };
const TEMPLATES = [{ id: "default", title: "Loja padrão", description: "Catálogo direto, responsivo e pronto para vender.", available: true }, { id: "editorial", title: "Editorial", description: "Mais espaço para coleções, história e imagens.", available: false }, { id: "minimal", title: "Minimal", description: "Uma experiência leve para um catálogo menor.", available: false }];
const CURRENCIES = [["BRL", "Real brasileiro (R$)"], ["USD", "Dólar americano (US$)"], ["EUR", "Euro (€)"], ["GBP", "Libra esterlina (£)"], ["ARS", "Peso argentino (ARS)"], ["CLP", "Peso chileno (CLP)"], ["MXN", "Peso mexicano (MXN)"]].map(([value, label]) => ({ value, label }));
const LOCALES = [["pt-BR", "Português — Brasil"], ["en-US", "English — United States"], ["es-ES", "Español — España"], ["es-MX", "Español — México"], ["fr-FR", "Français — France"], ["de-DE", "Deutsch — Deutschland"], ["it-IT", "Italiano — Italia"], ["ja-JP", "日本語 — 日本"]].map(([value, label]) => ({ value, label }));
const FALLBACK_TIMEZONES = ["America/Sao_Paulo", "America/Manaus", "America/Belem", "America/Fortaleza", "America/Recife", "America/Cuiaba", "America/Rio_Branco", "America/Porto_Velho", "America/Boa_Vista", "America/Noronha", "America/New_York", "America/Chicago", "America/Los_Angeles", "America/Argentina/Buenos_Aires", "Europe/Lisbon", "Europe/London", "Europe/Paris", "Europe/Berlin", "Asia/Tokyo", "Australia/Sydney", "UTC"];

export function TemplateAppearanceSection({ form, setForm }) {
  const storefront = getStorefront(form);
  const update = (key, value) => setForm((current) => ({ ...current, storefront: { ...getStorefront(current), [key]: value } }));
  const theme = (key, value) => update("theme", { ...storefront.theme, [key]: value.toUpperCase() });
  return <div className="space-y-4"><CollapsibleCard title="Template da vitrine" icon={LayoutTemplate} keepMounted defaultOpen><p className="mb-5 text-sm leading-6 text-muted-foreground">Escolha a estrutura que organiza a vitrine. Só modelos implementados podem ser ativados; os demais aparecem para você planejar a próxima mudança.</p><div className="grid gap-4 lg:grid-cols-3">{TEMPLATES.map((template) => <TemplateCard key={template.id} template={template} selected={storefront.template === template.id} color={form.color} onClick={() => template.available && update("template", template.id)} />)}</div></CollapsibleCard><CollapsibleCard title="Tema complementar" icon={Palette} keepMounted defaultOpen={false}><p className="mb-5 text-sm leading-6 text-muted-foreground">A cor principal e a fonte vêm da identidade. Ajuste aqui apenas os detalhes do tema que acompanham o template.</p><div className="grid gap-5 sm:grid-cols-2"><ColorField label="Cor secundária" value={storefront.theme.secondaryColor} onChange={(value) => theme("secondaryColor", value)} /><ColorField label="Cor de destaque" value={storefront.theme.accentColor} onChange={(value) => theme("accentColor", value)} /><ColorField label="Fundo" value={storefront.theme.backgroundColor} onChange={(value) => theme("backgroundColor", value)} /><ColorField label="Texto" value={storefront.theme.textColor} onChange={(value) => theme("textColor", value)} /></div><div className="mt-5"><Field label="URL HTTPS do favicon"><Input capitalization="none" type="url" value={storefront.faviconUrl || ""} onChange={(event) => update("faviconUrl", event.target.value)} placeholder="https://.../favicon.png" /></Field></div></CollapsibleCard></div>;
}

export function StoreOperationsSection({ form, setForm }) {
  const storefront = getStorefront(form);
  const update = (key, value) => setForm((current) => ({ ...current, storefront: { ...getStorefront(current), [key]: value } }));
  const timezoneOptions = Array.from(new Set([storefront.timezone, ...(typeof Intl.supportedValuesOf === "function" ? Intl.supportedValuesOf("timeZone") : FALLBACK_TIMEZONES)].filter(Boolean))).map((value) => ({ value, label: value.replace(/_/g, " ") }));
  return <div className="space-y-4"><CollapsibleCard title="Localização da loja" icon={MapPinned} keepMounted defaultOpen><p className="mb-5 text-sm leading-6 text-muted-foreground">Defina como datas, idioma e valores serão apresentados. A moeda de exibição não altera a moeda do Checkout Pro atual.</p><div className="grid gap-5 md:grid-cols-3"><SearchableSelect label="Fuso horário" value={storefront.timezone} options={timezoneOptions} placeholder="Busque um fuso horário" onChange={(value) => update("timezone", value)} /><SearchableSelect label="Moeda de exibição" value={storefront.currency} options={CURRENCIES} placeholder="Busque uma moeda" onChange={(value) => update("currency", value)} /><SearchableSelect label="Idioma e região" value={storefront.locale} options={LOCALES} placeholder="Busque um idioma" onChange={(value) => update("locale", value)} /></div></CollapsibleCard><CollapsibleCard title="Disponibilidade da vitrine" icon={Store} keepMounted defaultOpen={false}><div className="rounded-xl border p-4"><div className="flex items-start justify-between gap-4"><div><Label htmlFor="store-maintenance">Modo de manutenção</Label><p className="mt-1 text-xs leading-5 text-muted-foreground">Quando ativo, a vitrine informa indisponibilidade conforme o contrato público desta loja.</p></div><Switch id="store-maintenance" checked={Boolean(storefront.maintenance)} onCheckedChange={(value) => update("maintenance", value)} /></div>{storefront.maintenance ? <div className="mt-4"><Field label="Mensagem de manutenção"><Textarea value={storefront.maintenanceMessage || ""} onChange={(event) => update("maintenanceMessage", event.target.value)} maxLength="500" placeholder="Estamos em manutenção. Voltamos em breve." /></Field></div> : null}</div></CollapsibleCard></div>;
}

export function SalesDeliverySection({ form, setForm, storeId }) {
  const settings = { ...DEFAULT_SETTINGS, ...(form.settings || {}) };
  const [capabilities, setCapabilities] = useState(null);
  const [loading, setLoading] = useState(Boolean(storeId));
  const [error, setError] = useState("");
  const update = (key, value) => setForm((current) => ({ ...current, settings: { ...DEFAULT_SETTINGS, ...(current.settings || {}), [key]: value } }));
  useEffect(() => { let subscribed = true; if (!storeId) return undefined; setLoading(true); setError(""); api.getStorefrontCapabilities(storeId).then((result) => { if (subscribed) setCapabilities(result); }).catch((requestError) => { if (subscribed) setError(requestError.message || "Não foi possível carregar as opções das integrações."); }).finally(() => { if (subscribed) setLoading(false); }); return () => { subscribed = false; }; }, [storeId]);
  return <div className="space-y-4"><CollapsibleCard title="Regras comerciais de exibição" icon={CircleDollarSign} keepMounted defaultOpen><p className="mb-5 text-sm leading-6 text-muted-foreground">Defina o que a vitrine deve comunicar. A confirmação operacional de frete e pagamento continua nas integrações durante a compra.</p><div className="grid gap-5 md:grid-cols-3"><CurrencyInput label="Frete grátis a partir de" value={settings.freeShippingMinValue} onChange={(value) => update("freeShippingMinValue", value)} /><NumberField label="Máximo de parcelas" value={settings.maxInstallments} onChange={(value) => update("maxInstallments", value)} min="1" step="1" /><CurrencyInput label="Parcela mínima" value={settings.minInstallmentValue} onChange={(value) => update("minInstallmentValue", value)} /></div><div className="mt-5 grid gap-3 md:grid-cols-2">{[["showPriceFrom", "Exibir preço de origem"], ["showStock", "Exibir estoque"], ["showSoldCount", "Exibir contagem vendida"], ["allowGuestCheckout", "Permitir checkout como visitante"], ["requireCpf", "Solicitar CPF"], ["requirePhone", "Solicitar telefone"]].map(([key, label]) => <SwitchRow key={key} label={label} checked={Boolean(settings[key])} onChange={(value) => update(key, value)} />)}</div></CollapsibleCard><IntegrationMethods title="Meios de pagamento para comunicar" icon={CreditCard} integration={capabilities?.payments} loading={loading} error={error} methods={form.paymentMethods} disconnectedText="Conecte uma conta Mercado Pago em Integrações para carregar os meios ativos desta conta." helpText="O Checkout Pro confirma a disponibilidade final no pagamento. Aqui você decide o que a vitrine comunica." onChange={(paymentMethods) => setForm((current) => ({ ...current, paymentMethods }))} /><IntegrationMethods title="Serviços de frete para comunicar" icon={Truck} integration={capabilities?.shipping} loading={loading} error={error} methods={form.shippingMethods} disconnectedText="Conecte o Melhor Envio em Integrações para carregar os serviços disponíveis desta loja." helpText="Preço e prazo variam conforme CEP e itens do pedido. Esta escolha define os serviços que podem ser exibidos." onChange={(shippingMethods) => setForm((current) => ({ ...current, shippingMethods }))} /></div>;
}

function IntegrationMethods({ title, icon: Icon, integration, loading, error, methods, disconnectedText, helpText, onChange }) { const current = Array.isArray(methods) ? methods : []; const byId = new Map(current.map((method) => [method.id, method])); const options = integration?.options || []; const toggle = (option, enabled) => { const entry = { id: option.id, provider: option.provider, providerMethodId: option.providerMethodId, providerServiceId: option.providerServiceId, name: option.name, description: option.description, type: option.type, enabled }; onChange(byId.has(option.id) ? current.map((method) => method.id === option.id ? { ...method, ...entry } : method) : [...current, entry]); }; return <CollapsibleCard title={title} icon={Icon} keepMounted defaultOpen={false}><div className="flex flex-col gap-4 border-b pb-4 sm:flex-row sm:items-start sm:justify-between"><p className="max-w-2xl text-sm leading-6 text-muted-foreground">{helpText}</p><a href="/settings" className="inline-flex h-9 shrink-0 items-center gap-2 rounded-lg border px-3 text-sm font-semibold hover:bg-muted"><ExternalLink className="size-4" />Integrações</a></div>{loading ? <p className="py-5 text-sm text-muted-foreground">Carregando opções disponíveis…</p> : error ? <Notice tone="warning" text={error} /> : !integration?.connected ? <Notice text={disconnectedText} /> : !integration.available ? <Notice tone="warning" text={integration.error || "A conexão não retornou opções neste momento."} /> : !options.length ? <Notice text="A integração não retornou nenhuma opção ativa para esta conta." /> : <div className="mt-4 grid gap-3 md:grid-cols-2">{options.map((option) => <label key={option.id} className="flex cursor-pointer items-center justify-between gap-4 rounded-xl border p-3 transition hover:bg-muted/50"><span className="min-w-0"><strong className="block truncate text-sm">{option.name}</strong><small className="mt-1 block text-xs leading-5 text-muted-foreground">{option.description}</small></span><Switch checked={byId.get(option.id)?.enabled === true} onCheckedChange={(enabled) => toggle(option, enabled)} aria-label={`Comunicar ${option.name}`} /></label>)}</div>}<p className="mt-4 text-xs leading-5 text-muted-foreground">Configurações antigas são preservadas até você salvar uma nova seleção compatível.</p></CollapsibleCard>; }
function TemplateCard({ template, selected, color, onClick }) { return <button type="button" disabled={!template.available} aria-pressed={selected} onClick={onClick} className={`overflow-hidden rounded-xl border text-left transition ${selected ? "border-primary ring-2 ring-primary/25" : "hover:border-foreground/40"} ${template.available ? "" : "cursor-not-allowed opacity-60"}`}><div className="min-h-36 p-3" style={{ background: template.id === "default" ? `linear-gradient(140deg, ${color || "#FF32B2"} 0%, ${color || "#FF32B2"} 32%, #F8FAFC 32%)` : "linear-gradient(140deg,#F8FAFC,#E2E8F0)" }}><div className="ml-auto h-3 w-20 rounded bg-white/80" /><div className="mt-7 rounded-lg bg-white p-3 shadow-sm"><div className="h-2 w-2/3 rounded bg-slate-300" /><div className="mt-3 grid grid-cols-3 gap-2">{[1, 2, 3].map((item) => <span key={item} className="h-9 rounded bg-slate-100" />)}</div></div></div><div className="p-4"><div className="flex items-center justify-between gap-3"><strong className="text-sm">{template.title}</strong><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-wide ${selected ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{selected ? "Ativo" : template.available ? "Disponível" : "Em breve"}</span></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{template.description}</p></div></button>; }
function SearchableSelect({ label, value, options, placeholder, onChange }) { const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const selected = options.find((option) => option.value === value); const filtered = options.filter((option) => `${option.label} ${option.value}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"))).slice(0, 160); return <Field label={label}><div className="relative"><button type="button" aria-expanded={open} onClick={() => setOpen((current) => !current)} className="flex h-10 w-full items-center justify-between rounded-lg border bg-background px-3 text-left text-sm hover:bg-muted/40"><span className="truncate">{selected?.label || value || placeholder}</span><Globe2 className="size-4 shrink-0 text-muted-foreground" /></button>{open ? <div className="absolute z-30 mt-2 w-full overflow-hidden rounded-xl border bg-popover p-2 text-popover-foreground shadow-lg"><Input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder={placeholder} className="mb-2" /><div className="max-h-60 overflow-y-auto">{filtered.map((option) => <button key={option.value} type="button" onClick={() => { onChange(option.value); setOpen(false); setQuery(""); }} className={`block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-muted ${option.value === value ? "bg-muted font-semibold" : ""}`}><span className="block">{option.label}</span><span className="block text-xs text-muted-foreground">{option.value}</span></button>)}{!filtered.length ? <p className="p-3 text-sm text-muted-foreground">Nenhum resultado encontrado.</p> : null}</div></div> : null}</div></Field>; }
function CurrencyInput({ label, value, onChange }) { const formatted = value === null || value === undefined || value === "" ? "" : centsToCurrencyInput(Math.round(Number(value) * 100)); return <Field label={label}><div className="relative"><span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-sm font-semibold text-muted-foreground">R$</span><Input aria-label={label} value={formatted} inputMode="numeric" className="pl-10" placeholder="0,00" onChange={(event) => onChange(/\d/.test(event.target.value) ? currencyInputToCents(event.target.value) / 100 : null)} /></div></Field>; }
function ColorField({ label, value, onChange }) { const safe = /^#[0-9A-F]{6}$/i.test(value || "") ? value : "#000000"; return <Field label={label}><div className="flex gap-3"><Input type="color" value={safe} onChange={(event) => onChange(event.target.value)} className="h-10 w-12 p-1" /><Input capitalization="none" value={value || ""} onChange={(event) => onChange(event.target.value)} placeholder="#000000" maxLength="7" /></div></Field>; }
function NumberField({ label, value, onChange, ...props }) { return <Field label={label}><Input aria-label={label} type="number" inputMode="numeric" value={value ?? ""} onChange={(event) => onChange(event.target.value === "" ? null : Number(event.target.value))} {...props} /></Field>; }
function SwitchRow({ label, checked, onChange }) { return <label className="flex items-center justify-between gap-4 rounded-lg border p-3 text-sm font-medium"><span>{label}</span><Switch checked={checked} onCheckedChange={onChange} /></label>; }
function Notice({ tone = "neutral", text }) { const Icon = tone === "warning" ? AlertCircle : CheckCircle2; return <div className={`mt-4 flex gap-3 rounded-xl border p-4 text-sm leading-6 ${tone === "warning" ? "border-amber-500/30 bg-amber-500/10" : "bg-muted/40 text-muted-foreground"}`}><Icon className="mt-0.5 size-4 shrink-0" />{text}</div>; }
function Field({ label, children }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function getStorefront(form) { return { ...DEFAULT_STOREFRONT, ...(form.storefront || {}), theme: { ...DEFAULT_STOREFRONT.theme, ...(form.storefront?.theme || {}) } }; }
