import { CreditCard, PackageCheck, Settings2, SlidersHorizontal } from "lucide-react";
import { CollapsibleCard } from "@/components/CollapsibleCard";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";

const emptyPayment = () => ({ id: crypto.randomUUID(), name: "", icon: "", enabled: true, installments: null, minInstallmentValue: null, discount: null, daysToExpire: null });
const emptyShipping = () => ({ id: crypto.randomUUID(), name: "", description: "", minDays: null, maxDays: null, price: null, enabled: true });

export function StorefrontSettings({ form, setForm }) {
  const storefront = { maintenance: false, maintenanceMessage: "", currency: "BRL", locale: "pt-BR", timezone: "America/Sao_Paulo", template: "default", faviconUrl: "", theme: { secondaryColor: "", accentColor: "", backgroundColor: "", textColor: "" }, ...(form.storefront || {}) };
  const settings = { freeShippingMinValue: null, maxInstallments: null, minInstallmentValue: null, showPriceFrom: true, showStock: true, showSoldCount: false, allowGuestCheckout: true, requireCpf: false, requirePhone: true, ...(form.settings || {}) };
  const payments = Array.isArray(form.paymentMethods) ? form.paymentMethods : [];
  const shipping = Array.isArray(form.shippingMethods) ? form.shippingMethods : [];
  const updateStorefront = (key, value) => setForm((current) => ({ ...current, storefront: { ...storefront, [key]: value } }));
  const updateTheme = (key, value) => updateStorefront("theme", { ...storefront.theme, [key]: value.toUpperCase() });
  const updateSetting = (key, value) => setForm((current) => ({ ...current, settings: { ...settings, [key]: value } }));
  const updateList = (key, items) => setForm((current) => ({ ...current, [key]: items }));

  return <div className="space-y-6">
    <CollapsibleCard title="Vitrine e disponibilidade" icon={Settings2}>
      <p className="mb-5 text-sm leading-6 text-muted-foreground">Essas configurações representam a vitrine pública desta loja. Elas não criam pedidos de consumidor nem alteram as integrações de pagamento e frete.</p>
      <div className="grid gap-5 md:grid-cols-2"><Field label="Moeda"><Input capitalization="none" value={storefront.currency} onChange={(event) => updateStorefront("currency", event.target.value.toUpperCase())} maxLength="3" placeholder="BRL" /></Field><Field label="Locale"><Input capitalization="none" value={storefront.locale} onChange={(event) => updateStorefront("locale", event.target.value)} placeholder="pt-BR" /></Field><Field label="Fuso horário"><Input capitalization="none" value={storefront.timezone} onChange={(event) => updateStorefront("timezone", event.target.value)} placeholder="America/Sao_Paulo" /></Field><Field label="Template"><Input capitalization="none" value={storefront.template} onChange={(event) => updateStorefront("template", event.target.value)} maxLength="40" placeholder="default" /></Field></div>
      <div className="mt-5"><Field label="URL HTTPS do favicon"><Input capitalization="none" type="url" value={storefront.faviconUrl || ""} onChange={(event) => updateStorefront("faviconUrl", event.target.value)} placeholder="https://.../favicon.png" /></Field></div>
      <div className="mt-5 rounded-xl border p-4"><div className="flex items-center justify-between gap-4"><div><Label htmlFor="store-maintenance">Modo de manutenção</Label><p className="mt-1 text-xs leading-5 text-muted-foreground">Quando ativo, a vitrine pode informar indisponibilidade conforme o contrato público.</p></div><Switch id="store-maintenance" checked={Boolean(storefront.maintenance)} onCheckedChange={(value) => updateStorefront("maintenance", value)} /></div>{storefront.maintenance ? <div className="mt-4"><Field label="Mensagem de manutenção"><Textarea value={storefront.maintenanceMessage || ""} onChange={(event) => updateStorefront("maintenanceMessage", event.target.value)} maxLength="500" placeholder="Estamos em manutenção. Voltamos em breve." /></Field></div> : null}</div>
    </CollapsibleCard>
    <CollapsibleCard title="Tema complementar" icon={SlidersHorizontal}>
      <p className="mb-5 text-sm text-muted-foreground">A cor primária e a fonte continuam na seção Básico. Defina aqui os demais tokens do tema da vitrine.</p><div className="grid gap-5 sm:grid-cols-2"><ColorField label="Cor secundária" value={storefront.theme.secondaryColor} onChange={(value) => updateTheme("secondaryColor", value)} /><ColorField label="Cor de destaque" value={storefront.theme.accentColor} onChange={(value) => updateTheme("accentColor", value)} /><ColorField label="Fundo" value={storefront.theme.backgroundColor} onChange={(value) => updateTheme("backgroundColor", value)} /><ColorField label="Texto" value={storefront.theme.textColor} onChange={(value) => updateTheme("textColor", value)} /></div>
    </CollapsibleCard>
    <CollapsibleCard title="Regras comerciais de exibição" icon={CreditCard}>
      <p className="mb-5 text-sm leading-6 text-muted-foreground">São parâmetros declarativos do contrato da loja. Cobrança, credenciais e cálculo operacional seguem nas integrações existentes.</p><div className="grid gap-5 md:grid-cols-3"><NumberField label="Frete grátis a partir de" value={settings.freeShippingMinValue} onChange={(value) => updateSetting("freeShippingMinValue", value)} step="0.01" /><NumberField label="Máximo de parcelas" value={settings.maxInstallments} onChange={(value) => updateSetting("maxInstallments", value)} step="1" /><NumberField label="Parcela mínima" value={settings.minInstallmentValue} onChange={(value) => updateSetting("minInstallmentValue", value)} step="0.01" /></div><div className="mt-5 grid gap-3 md:grid-cols-2">{[["showPriceFrom", "Exibir preço de origem"], ["showStock", "Exibir estoque"], ["showSoldCount", "Exibir contagem vendida"], ["allowGuestCheckout", "Permitir checkout como visitante"], ["requireCpf", "Solicitar CPF"], ["requirePhone", "Solicitar telefone"]].map(([key, label]) => <SwitchRow key={key} label={label} checked={Boolean(settings[key])} onChange={(value) => updateSetting(key, value)} />)}</div>
    </CollapsibleCard>
    <MethodList title="Métodos de pagamento declarados" description="Cadastre somente formas que a sua operação efetivamente oferece. Isto não configura credenciais nem habilita um checkout." icon={CreditCard} items={payments} kind="paymentMethods" create={emptyPayment} fields={[["name", "Nome", "text"], ["installments", "Parcelas", "number"], ["minInstallmentValue", "Parcela mínima", "number"], ["discount", "Desconto (%)", "number"], ["daysToExpire", "Vencimento (dias)", "number"]]} onChange={updateList} />
    <MethodList title="Métodos de frete declarados" description="Informe as opções de entrega que a loja comunica. Cotações e etiquetas permanecem sob a integração de frete." icon={PackageCheck} items={shipping} kind="shippingMethods" create={emptyShipping} fields={[["name", "Nome", "text"], ["description", "Descrição", "text"], ["minDays", "Prazo mínimo", "number"], ["maxDays", "Prazo máximo", "number"], ["price", "Preço", "number"]]} onChange={updateList} />
  </div>;
}

function MethodList({ title, description, icon: Icon, items, kind, create, fields, onChange }) { const patch = (index, key, value) => onChange(kind, items.map((item, current) => current === index ? { ...item, [key]: value } : item)); return <CollapsibleCard title={title} icon={Icon}><p className="mb-5 text-sm leading-6 text-muted-foreground">{description}</p><div className="space-y-4">{items.map((item, index) => <div key={item.id || index} className="rounded-xl border p-4"><div className="grid gap-4 md:grid-cols-3">{fields.map(([key, label, type]) => <Field key={key} label={label}><Input type={type} capitalization={type === "text" ? "sentences" : "none"} inputMode={type === "number" ? "decimal" : undefined} value={item[key] ?? ""} onChange={(event) => patch(index, key, type === "number" ? optionalNumber(event.target.value) : event.target.value)} /></Field>)}</div><div className="mt-4 flex items-center justify-between gap-4"><SwitchRow label="Ativo" checked={item.enabled !== false} onChange={(value) => patch(index, "enabled", value)} /><Button type="button" variant="outline" className="text-destructive" onClick={() => onChange(kind, items.filter((_, current) => current !== index))}>Remover</Button></div></div>)}{!items.length ? <p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">Nenhum item configurado.</p> : null}</div><Button type="button" variant="outline" className="mt-4" onClick={() => onChange(kind, [...items, create()])}>Adicionar item</Button></CollapsibleCard>; }
function ColorField({ label, value, onChange }) { const safe = /^#[0-9A-F]{6}$/i.test(value || "") ? value : "#000000"; return <Field label={label}><div className="flex gap-3"><Input type="color" value={safe} onChange={(event) => onChange(event.target.value)} className="h-10 w-12 p-1" /><Input capitalization="none" value={value || ""} onChange={(event) => onChange(event.target.value)} placeholder="#000000" maxLength="7" /></div></Field>; }
function NumberField({ label, value, onChange, step }) { return <Field label={label}><Input type="number" inputMode="decimal" min="0" step={step} value={value ?? ""} onChange={(event) => onChange(optionalNumber(event.target.value))} /></Field>; }
function SwitchRow({ label, checked, onChange }) { return <label className="flex items-center justify-between gap-4 rounded-lg border p-3 text-sm font-medium"><span>{label}</span><Switch checked={checked} onCheckedChange={onChange} /></label>; }
function Field({ label, children }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function optionalNumber(value) { return value === "" ? null : Number(value); }
