import { one, query, transaction } from "../shared/repository.js";

export const withinTransaction = transaction;
export async function findOwnedStore(storeId, userId) { return one("SELECT id, name FROM ld_stores WHERE id = ? AND user_id = ?", [storeId, userId]); }
export async function findStore(storeId) { return one("SELECT id, name FROM ld_stores WHERE id = ?", [storeId]); }
export async function removePendingOAuthStates(storeId, provider) { await query("DELETE FROM ld_store_integration_oauth_states WHERE store_id = ? AND provider = ? AND consumed_at IS NULL", [storeId, provider]); }
export async function createOAuthState(record) { await query("INSERT INTO ld_store_integration_oauth_states (id, store_id, user_id, provider, state_hash, code_verifier_encrypted, expires_at, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", [record.id, record.storeId, record.userId, record.provider, record.stateHash, record.codeVerifierEncrypted, record.expiresAt, record.createdAt]); }
export async function findActiveOAuthState(provider, stateHash, timestamp) { return one("SELECT * FROM ld_store_integration_oauth_states WHERE provider = ? AND state_hash = ? AND consumed_at IS NULL AND expires_at > ?", [provider, stateHash, timestamp]); }
export async function consumeOAuthState(id, timestamp, db = { query }) { await db.query("UPDATE ld_store_integration_oauth_states SET consumed_at = ? WHERE id = ?", [timestamp, id]); }
export async function ensureEmailSettings(storeId, timestamp) { await query("INSERT IGNORE INTO ld_store_email_settings (store_id, created_at, updated_at) VALUES (?, ?, ?)", [storeId, timestamp, timestamp]); }
export async function ensureEmailTemplates(storeId, templates, timestamp) { for (const [eventKey, template] of Object.entries(templates)) await query("INSERT IGNORE INTO ld_store_email_templates (id, store_id, event_key, subject, body_html, enabled, created_at, updated_at) VALUES (?, ?, ?, ?, ?, 1, ?, ?)", [crypto.randomUUID(), storeId, eventKey, template.subject, template.bodyHtml, timestamp, timestamp]); }
export async function listIntegrations(storeId) { return query("SELECT * FROM ld_store_integrations WHERE store_id = ? ORDER BY provider", [storeId]); }
export async function findIntegration(storeId, provider) { return one("SELECT * FROM ld_store_integrations WHERE store_id = ? AND provider = ?", [storeId, provider]); }
export async function findConnectedIntegration(storeId, provider) { return one("SELECT * FROM ld_store_integrations WHERE store_id = ? AND provider = ? AND status = 'connected'", [storeId, provider]); }
export async function upsertIntegration(record, db = { query }) { await db.query("INSERT INTO ld_store_integrations (id, store_id, provider, status, account_email, config_encrypted, metadata_json, connected_at, last_tested_at, last_error, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, NULL, NULL, ?, ?) ON DUPLICATE KEY UPDATE status = VALUES(status), account_email = VALUES(account_email), config_encrypted = VALUES(config_encrypted), metadata_json = VALUES(metadata_json), connected_at = VALUES(connected_at), last_error = NULL, updated_at = VALUES(updated_at)", [record.id, record.storeId, record.provider, record.status, record.accountEmail, record.configEncrypted, record.metadataJson, record.connectedAt, record.createdAt, record.updatedAt]); }
export async function markIntegrationTest(storeId, provider, lastError, timestamp) { await query("UPDATE ld_store_integrations SET last_tested_at = ?, last_error = ?, updated_at = ? WHERE store_id = ? AND provider = ?", [timestamp, lastError, timestamp, storeId, provider]); }
export async function findEmailSettings(storeId) { return one("SELECT provider, from_name, from_email, reply_to, updated_at FROM ld_store_email_settings WHERE store_id = ?", [storeId]); }
export async function saveEmailSettings(storeId, input, timestamp) { await query("INSERT INTO ld_store_email_settings (store_id, provider, from_name, from_email, reply_to, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE provider = VALUES(provider), from_name = VALUES(from_name), from_email = VALUES(from_email), reply_to = VALUES(reply_to), updated_at = VALUES(updated_at)", [storeId, input.provider, input.fromName, input.fromEmail, input.replyTo, timestamp, timestamp]); }
export async function listEmailTemplates(storeId) { return query("SELECT event_key, subject, body_html, enabled, updated_at FROM ld_store_email_templates WHERE store_id = ? ORDER BY event_key", [storeId]); }
export async function findEmailTemplate(storeId, eventKey) { return one("SELECT event_key, subject, body_html, enabled, updated_at FROM ld_store_email_templates WHERE store_id = ? AND event_key = ?", [storeId, eventKey]); }
export async function updateEmailTemplate(storeId, eventKey, input, timestamp) { await query("UPDATE ld_store_email_templates SET subject = ?, body_html = ?, enabled = ?, updated_at = ? WHERE store_id = ? AND event_key = ?", [input.subject, input.bodyHtml, input.enabled, timestamp, storeId, eventKey]); }
export { one, query, transaction };
