export class IntegrationValidationError extends Error { constructor(status, message) { super(message); this.status = status; } }
export const integrationProviders = { mercadoPago: "mercado_pago", melhorEnvio: "melhor_envio", resend: "resend", smtp: "smtp" };
export const emailEvents = ["purchase_paid", "order_completed", "payment_requested", "customer_password_reset"];

export function requiredText(value, min, max, message) { const text = String(value || "").trim(); if (text.length < min || text.length > max) throw new IntegrationValidationError(422, message); return text; }
export function normalizeEmail(value) { const email = String(value || "").trim().toLowerCase(); return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) ? email : ""; }
export function normalizePostalCode(value) { const postalCode = String(value || "").replace(/\D/g, ""); return /^\d{8}$/.test(postalCode) ? postalCode : ""; }
export function parseMelhorEnvioInput(source = {}) { const accessToken = requiredText(source.accessToken, 20, 2000, "Informe o token da API do Melhor Envio."); const environment = source.environment ?? "production"; if (!["production", "sandbox"].includes(environment)) throw new IntegrationValidationError(422, "Informe um ambiente do Melhor Envio válido."); return { accessToken, originPostalCode: normalizePostalCode(source.originPostalCode), environment }; }
export function parseResendInput(source = {}) { return { apiKey: requiredText(source.apiKey, 8, 1000, "Informe a chave de API do Resend.") }; }
export function parseSmtpInput(source = {}) { const host = requiredText(source.host, 3, 255, "Informe o servidor SMTP."); const port = Number(source.port); if (!Number.isInteger(port) || port < 1 || port > 65535) throw new IntegrationValidationError(422, "Informe uma porta SMTP válida."); const username = requiredText(source.username, 1, 320, "Informe o usuário SMTP."); const password = requiredText(source.password, 1, 2000, "Informe a senha SMTP."); return { host, port, username, password, secure: Boolean(source.secure) }; }
export function parseEmailSettingsInput(source = {}) { const provider = [integrationProviders.resend, integrationProviders.smtp].includes(source.provider) ? source.provider : ""; const fromName = requiredText(source.fromName, 1, 120, "Informe o nome do remetente."); const fromEmail = normalizeEmail(source.fromEmail); const replyTo = String(source.replyTo || "").trim() ? normalizeEmail(source.replyTo) : ""; if (!provider || !fromEmail || (source.replyTo && !replyTo)) throw new IntegrationValidationError(422, "Informe um remetente válido, um provedor e, se houver, um e-mail de resposta válido."); return { provider, fromName, fromEmail, replyTo }; }
export function parseEmailTemplateInput(source = {}) { return { subject: requiredText(source.subject, 1, 200, "Informe o assunto do e-mail."), bodyHtml: requiredText(source.bodyHtml, 1, 30000, "Informe o conteúdo HTML do e-mail."), enabled: source.enabled === false ? 0 : 1 }; }
export function parseFreightQuote(source, metadata) { const from = normalizePostalCode(source?.originPostalCode || metadata?.originPostalCode); const to = normalizePostalCode(source?.destinationPostalCode); const products = Array.isArray(source?.products) ? source.products.map((product) => ({ id: requiredText(product?.id, 1, 80, "Informe a identificação do produto."), width: positiveNumber(product?.width, "Informe a largura do produto."), height: positiveNumber(product?.height, "Informe a altura do produto."), length: positiveNumber(product?.length, "Informe o comprimento do produto."), weight: positiveNumber(product?.weight, "Informe o peso do produto."), insurance_value: positiveNumber(product?.insuranceValue, "Informe o valor segurado do produto."), quantity: Math.max(1, Math.floor(positiveNumber(product?.quantity, "Informe a quantidade do produto."))) })) : []; if (!from || !to || !products.length) throw new IntegrationValidationError(422, "Informe CEP de origem, CEP de destino e pelo menos um produto com dimensões, peso, valor e quantidade."); return { from: { postal_code: from }, to: { postal_code: to }, products }; }
function positiveNumber(value, message) { const number = Number(value); if (!Number.isFinite(number) || number <= 0) throw new IntegrationValidationError(422, message); return number; }
